# Constrained Optimization (Energy Efficiency on Buildings)

### Dataset Information
The dataset is obtained from UCI Machine Learning Repository: https://archive.ics.uci.edu/ml/datasets/Energy+efficiency

The optimization objective is to minimize the heat energy needed for maintaining the temperature in building, with similar heating load and cooling load.

*Note:
<br>
1) Heating load is the amount of heat energy that would need to be added to a space to maintain the temperature in an acceptable range.
<br>
2) Cooling load is the amount of heat energy that would need to be removed from a space (cooling) to maintain the temperature in an acceptable range.

### Variable Information
1) X1: Relative Compactness

2) X2: Surface Area - m²

3) X3: Wall Area - m²

4) X4: Roof Area - m²

5) X5: Overall Height - m

6) X6: Orientation - 2:North, 3:East, 4:South, 5:West

7) X7: Glazing Area - 0%, 10%, 25%, 40% (of floor area)

8) X8: Glazing Area Distribution (Variance) - 1:Uniform, 2:North, 3:East, 4:South, 5:West

9) Y1: Heating Load - kWh/m²

10) Y2: Cooling Load - kWh/m²

In [1]:
import pandas as pd
import statsmodels.formula.api as smf

decimal = 4

In [2]:
# Load excel data into dataframe
df_init = pd.read_excel('../data/ENB2012_data.xlsx')

display(df_init[:5])
print('There\'re %d rows and %d variables in dataframe.' % (df_init.shape))

     X1     X2     X3      X4   X5  X6   X7  X8     Y1     Y2
0  0.98  514.5  294.0  110.25  7.0   2  0.0   0  15.55  21.33
1  0.98  514.5  294.0  110.25  7.0   3  0.0   0  15.55  21.33
2  0.98  514.5  294.0  110.25  7.0   4  0.0   0  15.55  21.33
3  0.98  514.5  294.0  110.25  7.0   5  0.0   0  15.55  21.33
4  0.90  563.5  318.5  122.50  7.0   2  0.0   0  20.84  28.28

There're 768 rows and 10 variables in dataframe.

In [3]:
# Drop categorical fields
df = df_init.drop(columns=['X6', 'X8'])
X_var = ['X1', 'X2', 'X3', 'X4', 'X5', 'X7']

display(df[:5])
print('There\'re %d rows and %d variables in dataframe.' % (df.shape))

     X1     X2     X3      X4   X5   X7     Y1     Y2
0  0.98  514.5  294.0  110.25  7.0  0.0  15.55  21.33
1  0.98  514.5  294.0  110.25  7.0  0.0  15.55  21.33
2  0.98  514.5  294.0  110.25  7.0  0.0  15.55  21.33
3  0.98  514.5  294.0  110.25  7.0  0.0  15.55  21.33
4  0.90  563.5  318.5  122.50  7.0  0.0  20.84  28.28

There're 768 rows and 8 variables in dataframe.

In [4]:
# Create fitted model (ordinary least squares regression) for variable Y1
lm1 = smf.ols(formula='Y1 ~ X1 + X2 + X3 + X4 + X5 + X7', data=df).fit()

display(lm1.summary())

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                     Y1   R-squared:                       0.915
Model:                            OLS   Adj. R-squared:                  0.915
Method:                 Least Squares   F-statistic:                     1646.
Date:                Sun, 19 May 2019   Prob (F-statistic):               0.00
Time:                        14:25:40   Log-Likelihood:                -1916.8
No. Observations:                 768   AIC:                             3846.
Df Residuals:                     762   BIC:                             3873.
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     84.3865     19.112      4.415      0.000      46.869     121.904
X1           -64.7734     10.334     -6.268      0.000     -85.059     -44.488
X2            -0.0626      0.013     -4.650      0.000      -0.089      -0.036
X3             0.0361      0.004      9.346      0.000       0.029       0.044
X4            -0.0494      0.008     -6.540      0.000      -0.064      -0.035
X5             4.1700      0.339     12.285      0.000       3.504       4.836
X7            20.4380      0.799     25.588      0.000      18.870      22.006
==============================================================================
Omnibus:                       20.756   Durbin-Watson:                   0.646
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               44.998
Skew:                          -0.002   Prob(JB):                     1.69e-10
Kurtosis:                       4.186   Cond. No.                     2.84e+16
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.64e-25. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [5]:
# Construct linear regression formula for variable Y1
lm1_formula = f'Y1 = {round(lm1.params[0], decimal)}'

for var in X_var:
    if lm1.params[var] < 0:
        lm1_formula += f' - {abs(round(lm1.params[var], decimal))} {var}'
    else:
        lm1_formula += f' + {round(lm1.params[var], decimal)} {var}'

print('Linear regression formula for Y1:')
print(lm1_formula)

Linear regression formula for Y1:
Y1 = 84.3865 - 64.7734 X1 - 0.0626 X2 + 0.0361 X3 - 0.0494 X4 + 4.17 X5 + 20.438 X7

In [6]:
# Create fitted model (ordinary least squares regression) for variable Y2
lm2 = smf.ols(formula='Y2 ~ X1 + X2 + X3 + X4 + X5 + X7', data=df).fit()

display(lm2.summary())

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                     Y2   R-squared:                       0.888
Model:                            OLS   Adj. R-squared:                  0.887
Method:                 Least Squares   F-statistic:                     1203.
Date:                Sun, 19 May 2019   Prob (F-statistic):               0.00
Time:                        14:25:40   Log-Likelihood:                -1980.2
No. Observations:                 768   AIC:                             3972.
Df Residuals:                     762   BIC:                             4000.
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     97.7618     20.756      4.710      0.000      57.015     138.508
X1           -70.7877     11.223     -6.307      0.000     -92.819     -48.756
X2            -0.0661      0.015     -4.520      0.000      -0.095      -0.037
X3             0.0225      0.004      5.366      0.000       0.014       0.031
X4            -0.0443      0.008     -5.405      0.000      -0.060      -0.028
X5             4.2838      0.369     11.620      0.000       3.560       5.008
X7            14.8180      0.867     17.082      0.000      13.115      16.521
==============================================================================
Omnibus:                      104.896   Durbin-Watson:                   1.095
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              232.225
Skew:                           0.766   Prob(JB):                     3.74e-51
Kurtosis:                       5.215   Cond. No.                     2.84e+16
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.64e-25. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [7]:
# Construct linear regression formula for variable Y2
lm2_formula = f'Y2 = {round(lm2.params[0], decimal)}'

for var in X_var:
    if lm2.params[var] < 0:
        lm2_formula += f' - {abs(round(lm2.params[var], decimal))} {var}'
    else:
        lm2_formula += f' + {round(lm2.params[var], decimal)} {var}'

print('Linear regression formula for Y2:')
print(lm2_formula)

Linear regression formula for Y2:
Y2 = 97.7618 - 70.7877 X1 - 0.0661 X2 + 0.0225 X3 - 0.0443 X4 + 4.2838 X5 + 14.818 X7

In [8]:
# Calculate difference between X2 and (X3 + X4), X3 and X4, Y1 and Y2
df['X2 - (X3 + X4)'] = round(df['X2'] - (df['X3'] + df['X4']), decimal)
df['X3 - X4'] = round(df['X3'] - df['X4'], decimal)
df['|Y1 - Y2|'] = abs(round(df['Y1'] - df['Y2'], decimal))
df['Avg(Y1, Y2)'] = round(df[['Y1', 'Y2']].mean(axis=1), decimal)

display(df[:5])

,X1,X2,X3,X4,X5,X7,Y1,Y2,X2 - (X3 + X4),X3 - X4,|Y1 - Y2|,"Avg(Y1, Y2)"
0,0.98,514.5,294.0,110.25,7.0,0.0,15.55,21.33,110.25,183.75,5.78,18.44
1,0.98,514.5,294.0,110.25,7.0,0.0,15.55,21.33,110.25,183.75,5.78,18.44
2,0.98,514.5,294.0,110.25,7.0,0.0,15.55,21.33,110.25,183.75,5.78,18.44
3,0.98,514.5,294.0,110.25,7.0,0.0,15.55,21.33,110.25,183.75,5.78,18.44
4,0.90,563.5,318.5,122.50,7.0,0.0,20.84,28.28,122.50,196.00,7.44,24.56

In [9]:
# Display descriptive statistics of variables
display(df.describe())

,X1,X2,X3,X4,X5,X7,Y1,Y2,X2 - (X3 + X4),X3 - X4,|Y1 - Y2|,"Avg(Y1, Y2)"
count,768.000000,768.000000,768.000000,768.000000,768.00000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,0.764167,671.708333,318.500000,176.604167,5.25000,0.234375,22.307195,24.587760,176.604167,141.895833,2.677622,23.447478
std,0.105777,88.086116,43.626481,45.165950,1.75114,0.133221,10.090204,9.513306,45.165950,71.380754,1.730804,9.742477
min,0.620000,514.500000,245.000000,110.250000,3.50000,0.000000,6.010000,10.900000,110.250000,24.500000,0.000000,8.475000
25%,0.682500,606.375000,294.000000,140.875000,3.50000,0.100000,12.992500,15.620000,140.875000,91.875000,1.280000,14.375000
50%,0.750000,673.750000,318.500000,183.750000,5.25000,0.250000,18.950000,22.080000,183.750000,147.000000,2.660000,20.485000
75%,0.830000,741.125000,343.000000,220.500000,7.00000,0.400000,31.667500,33.132500,220.500000,186.812500,3.480000,32.167500
max,0.980000,808.500000,416.500000,220.500000,7.00000,0.400000,43.100000,48.030000,220.500000,294.000000,10.690000,44.975000

In [10]:
# Construct constraints based on variable sign in formula and probability distribution of variables
print('Linear regression formula for Y1 and Y2:')
print('1) ' + lm1_formula)
print('2) ' + lm2_formula)

print('\nAs this is a minimization problem of Y1 and Y2,')
print('i) Use <= sign for variables with negative coefficient in formula.')
print('ii) Use >= sign for variables with positive coefficient in formula.')

print('\nFor example,')
print(f'The larger the value of X1 (coefficient = {round(lm1.params["X1"], decimal)}), the smaller the value of Y1.')
print('Hence constraint for X1 is using <= sign to limit its value.')

print('\nBased on probability distribution of variables,')
print('iii) Use maximum value for constraint from i).')
print('iv) Use minimum value for constraint from ii).')
print('v) Use median value for constraint involving two or more variables.')

print('\nConstraints:')
X1_upper_constr = df['X1'].max()
print(f'3) X1 <= {X1_upper_constr}')
X2_upper_constr = df['X2'].max()
print(f'4) X2 <= {X2_upper_constr}')
X5_lower_constr = df['X5'].min()
print(f'5) X5 >= {X5_lower_constr}')
X7_lower_constr = df['X7'].min()
print(f'6) X7 >= {X7_lower_constr}')

print('\nAs X2 (Surface Area) is always greater than sum of X3 (Wall Area) and X4 (Roof Area),')
X2X3X4_constr = df['X2 - (X3 + X4)'].median()
print(f'7) X3 + X4 + {X2X3X4_constr} <= X2')

print('\nAs X3 (Wall Area) is always greater than X4 (Roof Area),')
X3X4_constr = df['X3 - X4'].median()
print(f'8) X4 + {X3X4_constr} <= X3')

print('\nAs value of Y1 and Y2 needs to be similar to each other,')
Y1Y2_constr = df['|Y1 - Y2|'].median()
print(f'9) Y1 - Y2 <= {Y1Y2_constr}')
print(f'10) Y2 - Y1 <= {Y1Y2_constr}')

print('\nOther constraints with their minimum or maximum:')
X4_lower_constr = df['X4'].min()
print(f'11) X4 >= {X4_lower_constr}')
X5_upper_constr = df['X5'].max()
print(f'12) X5 <= {X5_upper_constr}')
X7_upper_constr = df['X7'].max()
print(f'13) X7 <= {X7_upper_constr}')
Y1Y2_lower_constr = df['Avg(Y1, Y2)'].min()
print(f'14) Y1, Y2 >= {Y1Y2_lower_constr}')
print('15) X1 >= 0')

Linear regression formula for Y1 and Y2:
1) Y1 = 84.3865 - 64.7734 X1 - 0.0626 X2 + 0.0361 X3 - 0.0494 X4 + 4.17 X5 + 20.438 X7
2) Y2 = 97.7618 - 70.7877 X1 - 0.0661 X2 + 0.0225 X3 - 0.0443 X4 + 4.2838 X5 + 14.818 X7

As this is a minimization problem of Y1 and Y2,
i) Use <= sign for variables with negative coefficient in formula.
ii) Use >= sign for variables with positive coefficient in formula.

For example,
The larger the value of X1 (coefficient = -64.7734), the smaller the value of Y1.
Hence constraint for X1 is using <= sign to limit its value.

Based on probability distribution of variables,
iii) Use maximum value for constraint from i).
iv) Use minimum value for constraint from ii).
v) Use median value for constraint involving two or more variables.

Constraints:
3) X1 <= 0.98
4) X2 <= 808.5
5) X5 >= 3.5
6) X7 >= 0.0

As X2 (Surface Area) is always greater than sum of X3 (Wall Area) and X4 (Roof Area),
7) X3 + X4 + 183.75 <= X2

As X3 (Wall Area) is always greater than X4 (Roof Area),
8) X4 + 147.0 <= X3

As value of Y1 and Y2 needs to be similar to each other,
9) Y1 - Y2 <= 2.66
10) Y2 - Y1 <= 2.66

Other constraints with their minimum or maximum:
11) X4 >= 110.25
12) X5 <= 7.0
13) X7 <= 0.4
14) Y1, Y2 >= 8.475
15) X1 >= 0

In [11]:
# Optimization problem
print('Minimize Z = Y1 + Y2, subject to,')
print('1) ' + lm1_formula)
print('2) ' + lm2_formula)
print(f'3) X1 <= {X1_upper_constr}')
print(f'4) X2 <= {X2_upper_constr}')
print(f'5) X5 >= {X5_lower_constr}')
print(f'6) X7 >= {X7_lower_constr}')
print(f'7) X3 + X4 + {X2X3X4_constr} <= X2')
print(f'8) X4 + {X3X4_constr} <= X3')
print(f'9) Y1 - Y2 <= {Y1Y2_constr}')
print(f'10) Y2 - Y1 <= {Y1Y2_constr}')
print(f'11) X4 >= {X4_lower_constr}')
print(f'12) X5 <= {X5_upper_constr}')
print(f'13) X7 <= {X7_upper_constr}')
print(f'14) Y1, Y2 >= {Y1Y2_lower_constr}')
print('15) X1 >= 0')

Minimize Z = Y1 + Y2, subject to,
1) Y1 = 84.3865 - 64.7734 X1 - 0.0626 X2 + 0.0361 X3 - 0.0494 X4 + 4.17 X5 + 20.438 X7
2) Y2 = 97.7618 - 70.7877 X1 - 0.0661 X2 + 0.0225 X3 - 0.0443 X4 + 4.2838 X5 + 14.818 X7
3) X1 <= 0.98
4) X2 <= 808.5
5) X5 >= 3.5
6) X7 >= 0.0
7) X3 + X4 + 183.75 <= X2
8) X4 + 147.0 <= X3
9) Y1 - Y2 <= 2.66
10) Y2 - Y1 <= 2.66
11) X4 >= 110.25
12) X5 <= 7.0
13) X7 <= 0.4
14) Y1, Y2 >= 8.475
15) X1 >= 0

In [12]:
# Convert the objective function and constraints with respect to variable Y1 and Y2
print(lm1_formula)
print(lm2_formula)


print('\nConverting objective function:')
print('Z = Y1 + Y2')
print('Z = (' + lm1_formula[5:] + ') + (' + lm2_formula[5:] + ')')

# Calculate Y1 + Y2
Z_intercept = round(round(lm1.params[0], decimal) + round(lm2.params[0], decimal), decimal)
X1_coef = round(round(lm1.params['X1'], decimal) + round(lm2.params['X1'], decimal), decimal)
X2_coef = round(round(lm1.params['X2'], decimal) + round(lm2.params['X2'], decimal), decimal)
X3_coef = round(round(lm1.params['X3'], decimal) + round(lm2.params['X3'], decimal), decimal)
X4_coef = round(round(lm1.params['X4'], decimal) + round(lm2.params['X4'], decimal), decimal)
X5_coef = round(round(lm1.params['X5'], decimal) + round(lm2.params['X5'], decimal), decimal)
X7_coef = round(round(lm1.params['X7'], decimal) + round(lm2.params['X7'], decimal), decimal)
X_var_coef = [X1_coef, X2_coef, X3_coef, X4_coef, X5_coef, X7_coef]

lm1_plus_lm2 = f'{Z_intercept}'
for var, coef in dict(zip(X_var, X_var_coef)).items():
    if coef < 0:
        lm1_plus_lm2 += f' - {abs(coef)} {var}'
    else:
        lm1_plus_lm2 += f' + {coef} {var}'

print('Z = ' + lm1_plus_lm2)


print('\nConverting constraint:')
print(f'Y1 - Y2 <= {Y1Y2_constr}')
print('(' + lm1_formula[5:] + ') - (' + lm2_formula[5:] + f') <= {Y1Y2_constr}')

# Calculate Y1 - Y2
lm1_minus_lm2 = f'{round(round(lm1.params[0], decimal) - round(lm2.params[0], decimal), decimal)}'
for var in X_var:
    if round(lm1.params[var], decimal) - round(lm2.params[var], decimal) < 0:
        lm1_minus_lm2 += ' - ' + \
            f'{abs(round(round(lm1.params[var], decimal) - round(lm2.params[var], decimal), decimal))} {var}'
    else:
        lm1_minus_lm2 += ' + ' + \
            f'{round(round(lm1.params[var], decimal) - round(lm2.params[var], decimal), decimal)} {var}'

print(lm1_minus_lm2 + f' <= {Y1Y2_constr}')
print(lm1_minus_lm2[7 + decimal:] + ' <= ' + \
      f'{round(Y1Y2_constr + -round(round(lm1.params[0], decimal) - round(lm2.params[0], decimal), decimal), decimal)}')


print('\nConverting constraint:')
print(f'Y2 - Y1 <= {Y1Y2_constr}')
print('(' + lm2_formula[5:] + ') - (' + lm1_formula[5:] + f') <= {Y1Y2_constr}')

# Calculate Y2 - Y1
lm2_minus_lm1 = f'{round(round(lm2.params[0], decimal) - round(lm1.params[0], decimal), decimal)}'
for var in X_var:
    if round(lm2.params[var], decimal) - round(lm1.params[var], decimal) < 0:
        lm2_minus_lm1 += ' - ' + \
            f'{abs(round(round(lm2.params[var], decimal) - round(lm1.params[var], decimal), decimal))} {var}'
    else:
        lm2_minus_lm1 += ' + ' + \
            f'{round(round(lm2.params[var], decimal) - round(lm1.params[var], decimal), decimal)} {var}'

print(lm2_minus_lm1 + f' <= {Y1Y2_constr}')
print(lm2_minus_lm1[4 + decimal:] + ' <= ' + \
      f'{round(Y1Y2_constr + -round(round(lm2.params[0], decimal) - round(lm1.params[0], decimal), decimal), decimal)}')


print('\nConverting constraint:')
print(f'Y1 >= {Y1Y2_lower_constr}')
print(lm1_formula[5:] + f' >= {Y1Y2_lower_constr}')
print(lm1_formula[9 + decimal:] + f' >= {Y1Y2_lower_constr + -round(lm1.params[0], decimal)}')


print('\nConverting constraint:')
print(f'Y2 >= {Y1Y2_lower_constr}')
print(lm2_formula[5:] + f' >= {Y1Y2_lower_constr}')
print(lm2_formula[9 + decimal:] + f' >= {Y1Y2_lower_constr + -round(lm2.params[0], decimal)}')

Y1 = 84.3865 - 64.7734 X1 - 0.0626 X2 + 0.0361 X3 - 0.0494 X4 + 4.17 X5 + 20.438 X7
Y2 = 97.7618 - 70.7877 X1 - 0.0661 X2 + 0.0225 X3 - 0.0443 X4 + 4.2838 X5 + 14.818 X7

Converting objective function:
Z = Y1 + Y2
Z = (84.3865 - 64.7734 X1 - 0.0626 X2 + 0.0361 X3 - 0.0494 X4 + 4.17 X5 + 20.438 X7) + (97.7618 - 70.7877 X1 - 0.0661 X2 + 0.0225 X3 - 0.0443 X4 + 4.2838 X5 + 14.818 X7)
Z = 182.1483 - 135.5611 X1 - 0.1287 X2 + 0.0586 X3 - 0.0937 X4 + 8.4538 X5 + 35.256 X7

Converting constraint:
Y1 - Y2 <= 2.66
(84.3865 - 64.7734 X1 - 0.0626 X2 + 0.0361 X3 - 0.0494 X4 + 4.17 X5 + 20.438 X7) - (97.7618 - 70.7877 X1 - 0.0661 X2 + 0.0225 X3 - 0.0443 X4 + 4.2838 X5 + 14.818 X7) <= 2.66
-13.3753 + 6.0143 X1 + 0.0035 X2 + 0.0136 X3 - 0.0051 X4 - 0.1138 X5 + 5.62 X7 <= 2.66
6.0143 X1 + 0.0035 X2 + 0.0136 X3 - 0.0051 X4 - 0.1138 X5 + 5.62 X7 <= 16.0353

Converting constraint:
Y2 - Y1 <= 2.66
(97.7618 - 70.7877 X1 - 0.0661 X2 + 0.0225 X3 - 0.0443 X4 + 4.2838 X5 + 14.818 X7) - (84.3865 - 64.7734 X1 - 0.0626 X2 + 0.0361 X3 - 0.0494 X4 + 4.17 X5 + 20.438 X7) <= 2.66
13.3753 - 6.0143 X1 - 0.0035 X2 - 0.0136 X3 + 0.0051 X4 + 0.1138 X5 - 5.62 X7 <= 2.66
- 6.0143 X1 - 0.0035 X2 - 0.0136 X3 + 0.0051 X4 + 0.1138 X5 - 5.62 X7 <= -10.7153

Converting constraint:
Y1 >= 8.475
84.3865 - 64.7734 X1 - 0.0626 X2 + 0.0361 X3 - 0.0494 X4 + 4.17 X5 + 20.438 X7 >= 8.475
- 64.7734 X1 - 0.0626 X2 + 0.0361 X3 - 0.0494 X4 + 4.17 X5 + 20.438 X7 >= -75.9115

Converting constraint:
Y2 >= 8.475
97.7618 - 70.7877 X1 - 0.0661 X2 + 0.0225 X3 - 0.0443 X4 + 4.2838 X5 + 14.818 X7 >= 8.475
- 70.7877 X1 - 0.0661 X2 + 0.0225 X3 - 0.0443 X4 + 4.2838 X5 + 14.818 X7 >= -89.2868

In [13]:
# Optimization problem after variable Y1 and Y2 conversion
print(f'Minimize Z = ' + lm1_plus_lm2 + ', subject to,')
print(f'1) X1 <= {X1_upper_constr}')
print(f'2) X2 <= {X2_upper_constr}')
print(f'3) X5 >= {X5_lower_constr}')
print(f'4) -X2 + X3 + X4 <= {-X2X3X4_constr}')
print(f'5) -X3 + X4 <= {-X3X4_constr}')
print('6) ' + lm1_minus_lm2[7 + decimal:] + ' <= ' + \
      f'{round(Y1Y2_constr + -round(round(lm1.params[0], decimal) - round(lm2.params[0], decimal), decimal), decimal)}')
print('7) ' + lm2_minus_lm1[4 + decimal:] + ' <= ' + \
      f'{round(Y1Y2_constr + -round(round(lm2.params[0], decimal) - round(lm1.params[0], decimal), decimal), decimal)}')
print(f'8) X4 >= {X4_lower_constr}')
print(f'9) X5 <= {X5_upper_constr}')
print(f'10) X7 <= {X7_upper_constr}')
print('11) ' + lm1_formula[9 + decimal:] + f' >= {Y1Y2_lower_constr + -round(lm1.params[0], decimal)}')
print('12) ' + lm2_formula[9 + decimal:] + f' >= {Y1Y2_lower_constr + -round(lm2.params[0], decimal)}')
print('13) X1, X7 >= 0')

Minimize Z = 182.1483 - 135.5611 X1 - 0.1287 X2 + 0.0586 X3 - 0.0937 X4 + 8.4538 X5 + 35.256 X7, subject to,
1) X1 <= 0.98
2) X2 <= 808.5
3) X5 >= 3.5
4) -X2 + X3 + X4 <= -183.75
5) -X3 + X4 <= -147.0
6) 6.0143 X1 + 0.0035 X2 + 0.0136 X3 - 0.0051 X4 - 0.1138 X5 + 5.62 X7 <= 16.0353
7) - 6.0143 X1 - 0.0035 X2 - 0.0136 X3 + 0.0051 X4 + 0.1138 X5 - 5.62 X7 <= -10.7153
8) X4 >= 110.25
9) X5 <= 7.0
10) X7 <= 0.4
11) - 64.7734 X1 - 0.0626 X2 + 0.0361 X3 - 0.0494 X4 + 4.17 X5 + 20.438 X7 >= -75.9115
12) - 70.7877 X1 - 0.0661 X2 + 0.0225 X3 - 0.0443 X4 + 4.2838 X5 + 14.818 X7 >= -89.2868
13) X1, X7 >= 0

In [14]:
# Iteration functions
def check_optimal(Cj_minus_Zj, maximization):
    if maximization:
        if all(val <= 0 for val in Cj_minus_Zj):
            print(f'{Cj_minus_Zj} are <= 0, optimal solution is found successfully!')
            return True
        else:
            print(f'Any of {Cj_minus_Zj} is not <= 0, optimal solution is not found yet.')
            print('Proceed to next step.')
            return False
    else:
        if all(val >= 0 for val in Cj_minus_Zj):
            print(f'{Cj_minus_Zj} are >= 0, optimal solution is found successfully!')
            return True
        else:
            print(f'Any of {Cj_minus_Zj} is not >= 0, optimal solution is not found yet.')
            print('Proceed to next step.')
            return False


def simplex_method(df_init, calc_cols, basic_var, maximize, max_iter_cnt, decimal=4):
    iter_cnt = 0
    print(f'Iteration {iter_cnt}:')
    
    cols = ['CBi', 'Basic Variable'] + calc_cols + ['Solution']
    df = df_init.loc[df_init['Basic Variable'].isin(['Cj'] + basic_var), cols].copy()
    display(df)

    # Calculate Zj = sum(CBi * aij) and Cj - Zj
    print('Calculate Zj and Cj - Zj:')

    df = df.append({'Basic Variable': 'Zj'}, ignore_index=True)
    df.loc[df['Basic Variable']=='Zj', calc_cols] = \
        round(df.loc[df['Basic Variable'].isin(basic_var), calc_cols].mul(
        df.loc[df['Basic Variable'].isin(basic_var), 'CBi'], axis=0
        ).sum(), decimal).values.tolist()

    df = df.append({'Basic Variable': 'Cj - Zj'}, ignore_index=True)
    df.loc[df['Basic Variable']=='Cj - Zj', calc_cols] = \
        round(df.loc[df['Basic Variable']=='Cj', calc_cols] - \
        df.loc[df['Basic Variable']=='Zj', calc_cols].values, decimal).values[0].tolist()

    display(df)

    # Check the optimality condition for Cj - Zj
    Cj_minus_Zj = df.loc[df['Basic Variable']=='Cj - Zj', calc_cols]
    if check_optimal(Cj_minus_Zj.values[0].tolist(), maximize):
        df_final = df.loc[df['Basic Variable'].isin(basic_var), ['Basic Variable', 'Solution']] \
            .set_index('Basic Variable')
        return df_final, iter_cnt

    # Iterations
    while iter_cnt < max_iter_cnt:
        iter_cnt += 1
        print(f'\nIteration {iter_cnt}:')
        
        # a) Find key column
        if maximize:
            key_col = Cj_minus_Zj.idxmax(axis=1).values[0]
            key_col_val = Cj_minus_Zj.max(axis=1).values[0]
            print(f'a) Key column is {key_col} because {key_col_val} is the largest value of Cj - Zj.')
        else:
            key_col = Cj_minus_Zj.idxmin(axis=1).values[0]
            key_col_val = Cj_minus_Zj.min(axis=1).values[0]
            print(f'a) Key column is {key_col} because {key_col_val} is the smallest value of Cj - Zj.')

        # b) Find key row
        print('b)')
        df.loc[(df['Basic Variable'].isin(basic_var)) & (df[key_col] != 0), 'Ratio'] = \
            round(df['Solution'] / df[key_col], decimal)
        display(df)
        Ratio = df.loc[(df['Basic Variable'].isin(basic_var)) & (df['Ratio'] >= 0), 'Ratio']
        if len(Ratio.values) == 0:
            print('All values of Ratio are negative or empty, there is no solution.')
            return None, iter_cnt
        key_row = df.loc[Ratio.idxmin(), 'Basic Variable']
        key_row_val = Ratio.min()
        print(f'Key row is {key_row} because {key_row_val} is the smallest non-negative value of Ratio.')

        # c) Find key element
        # d) Identify entering and departing variables
        key_elmnt_val = df.loc[df['Basic Variable']==key_row, key_col].values[0]
        print(f'c) Key element is {key_elmnt_val} located at ({key_row}, {key_col}).')
        print(f'd) {key_col} is entering variable while {key_row} is departing variable.')

        # e) Filling in the elements
        print('e) Filling in the elements:')
        df_i = df[cols].copy()
        df_i.loc[df_i['Basic Variable']==key_row] = \
            [df.loc[df['Basic Variable']=='Cj', key_col].values[0], key_col] + \
            round((df.loc[df['Basic Variable']==key_row, calc_cols + ['Solution']] / \
            key_elmnt_val), decimal).values[0].tolist()

        basic_var = [key_col if var==key_row else var for var in basic_var]
        basic_var_fill = [var for var in basic_var if var!=key_col]
        for var in basic_var_fill:
            df_i.loc[df_i['Basic Variable']==var, calc_cols + ['Solution']] = \
                round((df.loc[df['Basic Variable']==var, calc_cols + ['Solution']] - \
                df.loc[df['Basic Variable']==var, key_col].values[0] * \
                df.loc[df['Basic Variable']==key_row, calc_cols + ['Solution']].values[0] / \
                key_elmnt_val), decimal)

        #display(df_i)
        
        # Calculate Zj = sum(CBi * aij) and Cj - Zj
        #print('Calculate Zj and Cj - Zj:')

        df_i.loc[df_i['Basic Variable']=='Zj', calc_cols] = \
            round(df_i.loc[df_i['Basic Variable'].isin(basic_var), calc_cols].mul(
            df_i.loc[df_i['Basic Variable'].isin(basic_var), 'CBi'], axis=0
            ).sum(), decimal).values.tolist()

        df_i.loc[df_i['Basic Variable']=='Cj - Zj', calc_cols] = \
            round(df_i.loc[df_i['Basic Variable']=='Cj', calc_cols] - \
            df_i.loc[df_i['Basic Variable']=='Zj', calc_cols].values, decimal).values[0].tolist()

        display(df_i)
        
        # Check the optimality condition for Cj - Zj
        Cj_minus_Zj = df_i.loc[df_i['Basic Variable']=='Cj - Zj', calc_cols]
        if check_optimal(Cj_minus_Zj.values[0].tolist(), maximize):
            df_final = df_i.loc[df_i['Basic Variable'].isin(basic_var), ['Basic Variable', 'Solution']] \
                .set_index('Basic Variable')
            return df_final, iter_cnt
        
        df = df_i.copy()
    
    print(f'Iteration has reached the maximum limit {max_iter_cnt}.')
    return None, iter_cnt

In [15]:
# Solution
# Convert the objective function and constraints to standard form
print(f'Minimize Z = ' + lm1_plus_lm2 + \
      ' + 0 S1 + 0 S2 + 0 S3 + 0 S4 + 0 S5 + 0 S6 + 0 S7 + 0 S8 + 0 S9 + 0 S10 + 0 S11 + 0 S12' + \
      ', subject to,')
print(f'1) X1 + 0 X2 + 0 X3 + 0 X4 + 0 X5 + 0 X7 + S1 = {X1_upper_constr}')
print(f'2) 0 X1 + X2 + 0 X3 + 0 X4 + 0 X5 + 0 X7 + S2 = {X2_upper_constr}')
print(f'3) 0 X1 + 0 X2 + 0 X3 + 0 X4 + X5 + 0 X7 - S3 = {X5_lower_constr}')
print(f'4) 0 X1 - X2 + X3 + X4 + 0 X5 + 0 X7 + S4 = {-X2X3X4_constr}')
print(f'5) 0 X1 + 0 X2 - X3 + X4 + 0 X5 + 0 X7 + S5 = {-X3X4_constr}')
print('6) ' + lm1_minus_lm2[7 + decimal:] + ' + S6 = ' + \
      f'{round(Y1Y2_constr + -round(round(lm1.params[0], decimal) - round(lm2.params[0], decimal), decimal), decimal)}')
print('7) ' + lm2_minus_lm1[4 + decimal:] + ' + S7 = ' + \
      f'{round(Y1Y2_constr + -round(round(lm2.params[0], decimal) - round(lm1.params[0], decimal), decimal), decimal)}')
print(f'8) 0 X1 + 0 X2 + 0 X3 + X4 + 0 X5 + 0 X7 - S8 = {X4_lower_constr}')
print(f'9) 0 X1 + 0 X2 + 0 X3 + 0 X4 + X5 + 0 X7 + S9 = {X5_upper_constr}')
print(f'10) 0 X1 + 0 X2 + 0 X3 + 0 X4 + 0 X5 + X7 + S10 = {X7_upper_constr}')
print('11) ' + lm1_formula[9 + decimal:] + f' - S11 = {Y1Y2_lower_constr + -round(lm1.params[0], decimal)}')
print('12) ' + lm2_formula[9 + decimal:] + f' - S12 = {Y1Y2_lower_constr + -round(lm2.params[0], decimal)}')
print('13) X1, X7, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, S11, S12 >= 0')

Minimize Z = 182.1483 - 135.5611 X1 - 0.1287 X2 + 0.0586 X3 - 0.0937 X4 + 8.4538 X5 + 35.256 X7 + 0 S1 + 0 S2 + 0 S3 + 0 S4 + 0 S5 + 0 S6 + 0 S7 + 0 S8 + 0 S9 + 0 S10 + 0 S11 + 0 S12, subject to,
1) X1 + 0 X2 + 0 X3 + 0 X4 + 0 X5 + 0 X7 + S1 = 0.98
2) 0 X1 + X2 + 0 X3 + 0 X4 + 0 X5 + 0 X7 + S2 = 808.5
3) 0 X1 + 0 X2 + 0 X3 + 0 X4 + X5 + 0 X7 - S3 = 3.5
4) 0 X1 - X2 + X3 + X4 + 0 X5 + 0 X7 + S4 = -183.75
5) 0 X1 + 0 X2 - X3 + X4 + 0 X5 + 0 X7 + S5 = -147.0
6) 6.0143 X1 + 0.0035 X2 + 0.0136 X3 - 0.0051 X4 - 0.1138 X5 + 5.62 X7 + S6 = 16.0353
7) - 6.0143 X1 - 0.0035 X2 - 0.0136 X3 + 0.0051 X4 + 0.1138 X5 - 5.62 X7 + S7 = -10.7153
8) 0 X1 + 0 X2 + 0 X3 + X4 + 0 X5 + 0 X7 - S8 = 110.25
9) 0 X1 + 0 X2 + 0 X3 + 0 X4 + X5 + 0 X7 + S9 = 7.0
10) 0 X1 + 0 X2 + 0 X3 + 0 X4 + 0 X5 + X7 + S10 = 0.4
11) - 64.7734 X1 - 0.0626 X2 + 0.0361 X3 - 0.0494 X4 + 4.17 X5 + 20.438 X7 - S11 = -75.9115
12) - 70.7877 X1 - 0.0661 X2 + 0.0225 X3 - 0.0443 X4 + 4.2838 X5 + 14.818 X7 - S12 = -89.2868
13) X1, X7, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, S11, S12 >= 0

In [16]:
# Solution
# Transform the standard form to initial simplex table
basic_var = ['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8', 'S9', 'S10', 'S11', 'S12'] # Cannot have 'Zj'
calc_cols = X_var + basic_var
cols = ['CBi', 'Basic Variable'] + calc_cols + ['Solution'] # Must have 'CBi', 'Basic Variable',
                                                            # 'Solution' columns
basic_row_Cj = [None, 'Cj', X1_coef, X2_coef, X3_coef, X4_coef, X5_coef, X7_coef,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None] # Must have 'Cj' row
basic_row_S1 = [0, basic_var[0], 1, 0, 0, 0, 0, 0,
                1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, X1_upper_constr]
basic_row_S2 = [0, basic_var[1], 0, 1, 0, 0, 0, 0,
                0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, X2_upper_constr]
basic_row_S3 = [0, basic_var[2], 0, 0, 0, 0, 1, 0,
                0, 0, - 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, X5_lower_constr]
basic_row_S4 = [0, basic_var[3], 0, - 1, 1, 1, 0, 0,
                0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, -X2X3X4_constr]
basic_row_S5 = [0, basic_var[4], 0, 0, - 1, 1, 0, 0,
                0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, -X3X4_constr]
basic_row_S6 = [0, basic_var[5],
                round(round(lm1.params['X1'], decimal) - round(lm2.params['X1'], decimal), decimal),
                round(round(lm1.params['X2'], decimal) - round(lm2.params['X2'], decimal), decimal),
                round(round(lm1.params['X3'], decimal) - round(lm2.params['X3'], decimal), decimal),
                round(round(lm1.params['X4'], decimal) - round(lm2.params['X4'], decimal), decimal),
                round(round(lm1.params['X5'], decimal) - round(lm2.params['X5'], decimal), decimal),
                round(round(lm1.params['X7'], decimal) - round(lm2.params['X7'], decimal), decimal),
                0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
                round(Y1Y2_constr + -round(round(lm1.params[0], decimal) - round(lm2.params[0], decimal), decimal), decimal)]
basic_row_S7 = [0, basic_var[6],
                round(round(lm2.params['X1'], decimal) - round(lm1.params['X1'], decimal), decimal),
                round(round(lm2.params['X2'], decimal) - round(lm1.params['X2'], decimal), decimal),
                round(round(lm2.params['X3'], decimal) - round(lm1.params['X3'], decimal), decimal),
                round(round(lm2.params['X4'], decimal) - round(lm1.params['X4'], decimal), decimal),
                round(round(lm2.params['X5'], decimal) - round(lm1.params['X5'], decimal), decimal),
                round(round(lm2.params['X7'], decimal) - round(lm1.params['X7'], decimal), decimal),
                0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
                round(Y1Y2_constr + -round(round(lm2.params[0], decimal) - round(lm1.params[0], decimal), decimal), decimal)]
basic_row_S8 = [0, basic_var[7], 0, 0, 0, 1, 0, 0,
                0, 0, 0, 0, 0, 0, 0, - 1, 0, 0, 0, 0, X4_lower_constr]
basic_row_S9 = [0, basic_var[8], 0, 0, 0, 0, 1, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, X5_upper_constr]
basic_row_S10 = [0, basic_var[9], 0, 0, 0, 0, 0, 1,
                 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, X7_upper_constr]
basic_row_S11 = [0, basic_var[10],
                 round(lm1.params['X1'], decimal),
                 round(lm1.params['X2'], decimal),
                 round(lm1.params['X3'], decimal),
                 round(lm1.params['X4'], decimal),
                 round(lm1.params['X5'], decimal),
                 round(lm1.params['X7'], decimal),
                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, - 1, 0,
                 Y1Y2_lower_constr + -round(lm1.params[0], decimal)]
basic_row_S12 = [0, basic_var[11],
                 round(lm2.params['X1'], decimal),
                 round(lm2.params['X2'], decimal),
                 round(lm2.params['X3'], decimal),
                 round(lm2.params['X4'], decimal),
                 round(lm2.params['X5'], decimal),
                 round(lm2.params['X7'], decimal),
                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, - 1,
                 Y1Y2_lower_constr + -round(lm2.params[0], decimal)]
data = [basic_row_Cj, basic_row_S1, basic_row_S2, basic_row_S3, basic_row_S4, basic_row_S5, basic_row_S6, basic_row_S7,
       basic_row_S8, basic_row_S9, basic_row_S10, basic_row_S11, basic_row_S12]
df_simpx_init = pd.DataFrame(data, columns=cols)

maximize = False
max_iter_cnt = 20

df_simpx_final, iter_cnt = simplex_method(df_simpx_init, calc_cols, basic_var, maximize, max_iter_cnt, decimal * 2)
print(f'{iter_cnt} iterations taken.')
print('Final solution:')
display(df_simpx_final)

Iteration 0:

,CBi,Basic Variable,X1,X2,X3,X4,X5,X7,S1,S2,...,S4,S5,S6,S7,S8,S9,S10,S11,S12,Solution
0,NaN,Cj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,0,0,...,0,0,0,0,0,0,0,0,0,NaN
1,0.0,S1,1.0000,0.0000,0.0000,0.0000,0.0000,0.000,1,0,...,0,0,0,0,0,0,0,0,0,0.9800
2,0.0,S2,0.0000,1.0000,0.0000,0.0000,0.0000,0.000,0,1,...,0,0,0,0,0,0,0,0,0,808.5000
3,0.0,S3,0.0000,0.0000,0.0000,0.0000,1.0000,0.000,0,0,...,0,0,0,0,0,0,0,0,0,3.5000
4,0.0,S4,0.0000,-1.0000,1.0000,1.0000,0.0000,0.000,0,0,...,1,0,0,0,0,0,0,0,0,-183.7500
5,0.0,S5,0.0000,0.0000,-1.0000,1.0000,0.0000,0.000,0,0,...,0,1,0,0,0,0,0,0,0,-147.0000
6,0.0,S6,6.0143,0.0035,0.0136,-0.0051,-0.1138,5.620,0,0,...,0,0,1,0,0,0,0,0,0,16.0353
7,0.0,S7,-6.0143,-0.0035,-0.0136,0.0051,0.1138,-5.620,0,0,...,0,0,0,1,0,0,0,0,0,-10.7153
8,0.0,S8,0.0000,0.0000,0.0000,1.0000,0.0000,0.000,0,0,...,0,0,0,0,-1,0,0,0,0,110.2500
9,0.0,S9,0.0000,0.0000,0.0000,0.0000,1.0000,0.000,0,0,...,0,0,0,0,0,1,0,0,0,7.0000
10,0.0,S10,0.0000,0.0000,0.0000,0.0000,0.0000,1.000,0,0,...,0,0,0,0,0,0,1,0,0,0.4000
11,0.0,S11,-64.7734,-0.0626,0.0361,-0.0494,4.1700,20.438,0,0,...,0,0,0,0,0,0,0,-1,0,-75.9115
12,0.0,S12,-70.7877,-0.0661,0.0225,-0.0443,4.2838,14.818,0,0,...,0,0,0,0,0,0,0,0,-1,-89.2868

Calculate Zj and Cj - Zj:

,CBi,Basic Variable,X1,X2,X3,X4,X5,X7,S1,S2,...,S4,S5,S6,S7,S8,S9,S10,S11,S12,Solution
0,NaN,Cj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1,0.0,S1,1.0000,0.0000,0.0000,0.0000,0.0000,0.000,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.9800
2,0.0,S2,0.0000,1.0000,0.0000,0.0000,0.0000,0.000,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,808.5000
3,0.0,S3,0.0000,0.0000,0.0000,0.0000,1.0000,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.5000
4,0.0,S4,0.0000,-1.0000,1.0000,1.0000,0.0000,0.000,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-183.7500
5,0.0,S5,0.0000,0.0000,-1.0000,1.0000,0.0000,0.000,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-147.0000
6,0.0,S6,6.0143,0.0035,0.0136,-0.0051,-0.1138,5.620,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,16.0353
7,0.0,S7,-6.0143,-0.0035,-0.0136,0.0051,0.1138,-5.620,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,-10.7153
8,0.0,S8,0.0000,0.0000,0.0000,1.0000,0.0000,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,110.2500
9,0.0,S9,0.0000,0.0000,0.0000,0.0000,1.0000,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,7.0000
10,0.0,S10,0.0000,0.0000,0.0000,0.0000,0.0000,1.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.4000
11,0.0,S11,-64.7734,-0.0626,0.0361,-0.0494,4.1700,20.438,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,-75.9115
12,0.0,S12,-70.7877,-0.0661,0.0225,-0.0443,4.2838,14.818,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-89.2868
13,NaN,Zj,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
14,NaN,Cj - Zj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

Any of [-135.5611, -0.1287, 0.0586, -0.0937, 8.4538, 35.256, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] is not >= 0, optimal solution is not found yet.
Proceed to next step.

Iteration 1:
a) Key column is X1 because -135.5611 is the smallest value of Cj - Zj.
b)

,CBi,Basic Variable,X1,X2,X3,X4,X5,X7,S1,S2,...,S5,S6,S7,S8,S9,S10,S11,S12,Solution,Ratio
0,NaN,Cj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1,0.0,S1,1.0000,0.0000,0.0000,0.0000,0.0000,0.000,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.9800,0.980000
2,0.0,S2,0.0000,1.0000,0.0000,0.0000,0.0000,0.000,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,808.5000,NaN
3,0.0,S3,0.0000,0.0000,0.0000,0.0000,1.0000,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.5000,NaN
4,0.0,S4,0.0000,-1.0000,1.0000,1.0000,0.0000,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-183.7500,NaN
5,0.0,S5,0.0000,0.0000,-1.0000,1.0000,0.0000,0.000,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-147.0000,NaN
6,0.0,S6,6.0143,0.0035,0.0136,-0.0051,-0.1138,5.620,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,16.0353,2.666196
7,0.0,S7,-6.0143,-0.0035,-0.0136,0.0051,0.1138,-5.620,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,-10.7153,1.781637
8,0.0,S8,0.0000,0.0000,0.0000,1.0000,0.0000,0.000,0.0,0.0,...,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,110.2500,NaN
9,0.0,S9,0.0000,0.0000,0.0000,0.0000,1.0000,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,7.0000,NaN
10,0.0,S10,0.0000,0.0000,0.0000,0.0000,0.0000,1.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.4000,NaN
11,0.0,S11,-64.7734,-0.0626,0.0361,-0.0494,4.1700,20.438,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,-75.9115,1.171955
12,0.0,S12,-70.7877,-0.0661,0.0225,-0.0443,4.2838,14.818,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-89.2868,1.261332
13,NaN,Zj,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
14,NaN,Cj - Zj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN

Key row is S1 because 0.98 is the smallest non-negative value of Ratio.
c) Key element is 1.0 located at (S1, X1).
d) X1 is entering variable while S1 is departing variable.
e) Filling in the elements:

,CBi,Basic Variable,X1,X2,X3,X4,X5,X7,S1,S2,...,S4,S5,S6,S7,S8,S9,S10,S11,S12,Solution
0,NaN,Cj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,0.0000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1,-135.5611,X1,1.0000,0.0000,0.0000,0.0000,0.0000,0.000,1.0000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.980000
2,0.0000,S2,0.0000,1.0000,0.0000,0.0000,0.0000,0.000,0.0000,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,808.500000
3,0.0000,S3,0.0000,0.0000,0.0000,0.0000,1.0000,0.000,0.0000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.500000
4,0.0000,S4,0.0000,-1.0000,1.0000,1.0000,0.0000,0.000,0.0000,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-183.750000
5,0.0000,S5,0.0000,0.0000,-1.0000,1.0000,0.0000,0.000,0.0000,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-147.000000
6,0.0000,S6,0.0000,0.0035,0.0136,-0.0051,-0.1138,5.620,-6.0143,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,10.141286
7,0.0000,S7,0.0000,-0.0035,-0.0136,0.0051,0.1138,-5.620,6.0143,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,-4.821286
8,0.0000,S8,0.0000,0.0000,0.0000,1.0000,0.0000,0.000,0.0000,0.0,...,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,110.250000
9,0.0000,S9,0.0000,0.0000,0.0000,0.0000,1.0000,0.000,0.0000,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,7.000000
10,0.0000,S10,0.0000,0.0000,0.0000,0.0000,0.0000,1.000,0.0000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.400000
11,0.0000,S11,0.0000,-0.0626,0.0361,-0.0494,4.1700,20.438,64.7734,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,-12.433568
12,0.0000,S12,0.0000,-0.0661,0.0225,-0.0443,4.2838,14.818,70.7877,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-19.914854
13,NaN,Zj,-135.5611,0.0000,0.0000,0.0000,0.0000,0.000,-135.5611,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
14,NaN,Cj - Zj,0.0000,-0.1287,0.0586,-0.0937,8.4538,35.256,135.5611,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

Any of [0.0, -0.1287, 0.0586, -0.0937, 8.4538, 35.256, 135.5611, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] is not >= 0, optimal solution is not found yet.
Proceed to next step.

Iteration 2:
a) Key column is X2 because -0.1287 is the smallest value of Cj - Zj.
b)

,CBi,Basic Variable,X1,X2,X3,X4,X5,X7,S1,S2,...,S5,S6,S7,S8,S9,S10,S11,S12,Solution,Ratio
0,NaN,Cj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,0.0000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1,-135.5611,X1,1.0000,0.0000,0.0000,0.0000,0.0000,0.000,1.0000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.980000,NaN
2,0.0000,S2,0.0000,1.0000,0.0000,0.0000,0.0000,0.000,0.0000,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,808.500000,808.500000
3,0.0000,S3,0.0000,0.0000,0.0000,0.0000,1.0000,0.000,0.0000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.500000,NaN
4,0.0000,S4,0.0000,-1.0000,1.0000,1.0000,0.0000,0.000,0.0000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-183.750000,183.750000
5,0.0000,S5,0.0000,0.0000,-1.0000,1.0000,0.0000,0.000,0.0000,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-147.000000,NaN
6,0.0000,S6,0.0000,0.0035,0.0136,-0.0051,-0.1138,5.620,-6.0143,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,10.141286,2897.510286
7,0.0000,S7,0.0000,-0.0035,-0.0136,0.0051,0.1138,-5.620,6.0143,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,-4.821286,1377.510286
8,0.0000,S8,0.0000,0.0000,0.0000,1.0000,0.0000,0.000,0.0000,0.0,...,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,110.250000,NaN
9,0.0000,S9,0.0000,0.0000,0.0000,0.0000,1.0000,0.000,0.0000,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,7.000000,NaN
10,0.0000,S10,0.0000,0.0000,0.0000,0.0000,0.0000,1.000,0.0000,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.400000,NaN
11,0.0000,S11,0.0000,-0.0626,0.0361,-0.0494,4.1700,20.438,64.7734,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,-12.433568,198.619297
12,0.0000,S12,0.0000,-0.0661,0.0225,-0.0443,4.2838,14.818,70.7877,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-19.914854,301.283722
13,NaN,Zj,-135.5611,0.0000,0.0000,0.0000,0.0000,0.000,-135.5611,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
14,NaN,Cj - Zj,0.0000,-0.1287,0.0586,-0.0937,8.4538,35.256,135.5611,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN

Key row is S4 because 183.75 is the smallest non-negative value of Ratio.
c) Key element is -1.0 located at (S4, X2).
d) X2 is entering variable while S4 is departing variable.
e) Filling in the elements:

,CBi,Basic Variable,X1,X2,X3,X4,X5,X7,S1,S2,...,S4,S5,S6,S7,S8,S9,S10,S11,S12,Solution
0,NaN,Cj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,0.0000,0.0,...,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1,-135.5611,X1,1.0000,0.0000,0.0000,0.0000,0.0000,0.000,1.0000,0.0,...,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.980000
2,0.0000,S2,0.0000,0.0000,1.0000,1.0000,0.0000,0.000,0.0000,1.0,...,1.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,624.750000
3,0.0000,S3,0.0000,0.0000,0.0000,0.0000,1.0000,0.000,0.0000,0.0,...,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.500000
4,-0.1287,X2,-0.0000,1.0000,-1.0000,-1.0000,-0.0000,-0.000,-0.0000,-0.0,...,-1.0000,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,183.750000
5,0.0000,S5,0.0000,0.0000,-1.0000,1.0000,0.0000,0.000,0.0000,0.0,...,0.0000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-147.000000
6,0.0000,S6,0.0000,0.0000,0.0171,-0.0016,-0.1138,5.620,-6.0143,0.0,...,0.0035,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,9.498161
7,0.0000,S7,0.0000,0.0000,-0.0171,0.0016,0.1138,-5.620,6.0143,0.0,...,-0.0035,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,-4.178161
8,0.0000,S8,0.0000,0.0000,0.0000,1.0000,0.0000,0.000,0.0000,0.0,...,0.0000,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,110.250000
9,0.0000,S9,0.0000,0.0000,0.0000,0.0000,1.0000,0.000,0.0000,0.0,...,0.0000,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,7.000000
10,0.0000,S10,0.0000,0.0000,0.0000,0.0000,0.0000,1.000,0.0000,0.0,...,0.0000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.400000
11,0.0000,S11,0.0000,0.0000,-0.0265,-0.1120,4.1700,20.438,64.7734,0.0,...,-0.0626,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,-0.930818
12,0.0000,S12,0.0000,0.0000,-0.0436,-0.1104,4.2838,14.818,70.7877,0.0,...,-0.0661,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-7.768979
13,NaN,Zj,-135.5611,-0.1287,0.1287,0.1287,0.0000,0.000,-135.5611,0.0,...,0.1287,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
14,NaN,Cj - Zj,0.0000,0.0000,-0.0701,-0.2224,8.4538,35.256,135.5611,0.0,...,-0.1287,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

Any of [0.0, 0.0, -0.0701, -0.2224, 8.4538, 35.256, 135.5611, 0.0, 0.0, -0.1287, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] is not >= 0, optimal solution is not found yet.
Proceed to next step.

Iteration 3:
a) Key column is X4 because -0.2224 is the smallest value of Cj - Zj.
b)

,CBi,Basic Variable,X1,X2,X3,X4,X5,X7,S1,S2,...,S5,S6,S7,S8,S9,S10,S11,S12,Solution,Ratio
0,NaN,Cj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,0.0000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1,-135.5611,X1,1.0000,0.0000,0.0000,0.0000,0.0000,0.000,1.0000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.980000,NaN
2,0.0000,S2,0.0000,0.0000,1.0000,1.0000,0.0000,0.000,0.0000,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,624.750000,624.750000
3,0.0000,S3,0.0000,0.0000,0.0000,0.0000,1.0000,0.000,0.0000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.500000,NaN
4,-0.1287,X2,-0.0000,1.0000,-1.0000,-1.0000,-0.0000,-0.000,-0.0000,-0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,183.750000,-183.750000
5,0.0000,S5,0.0000,0.0000,-1.0000,1.0000,0.0000,0.000,0.0000,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-147.000000,-147.000000
6,0.0000,S6,0.0000,0.0000,0.0171,-0.0016,-0.1138,5.620,-6.0143,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,9.498161,-5936.350625
7,0.0000,S7,0.0000,0.0000,-0.0171,0.0016,0.1138,-5.620,6.0143,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,-4.178161,-2611.350625
8,0.0000,S8,0.0000,0.0000,0.0000,1.0000,0.0000,0.000,0.0000,0.0,...,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,110.250000,110.250000
9,0.0000,S9,0.0000,0.0000,0.0000,0.0000,1.0000,0.000,0.0000,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,7.000000,NaN
10,0.0000,S10,0.0000,0.0000,0.0000,0.0000,0.0000,1.000,0.0000,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.400000,NaN
11,0.0000,S11,0.0000,0.0000,-0.0265,-0.1120,4.1700,20.438,64.7734,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,-0.930818,8.310875
12,0.0000,S12,0.0000,0.0000,-0.0436,-0.1104,4.2838,14.818,70.7877,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-7.768979,70.371187
13,NaN,Zj,-135.5611,-0.1287,0.1287,0.1287,0.0000,0.000,-135.5611,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
14,NaN,Cj - Zj,0.0000,0.0000,-0.0701,-0.2224,8.4538,35.256,135.5611,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN

Key row is S11 because 8.310875 is the smallest non-negative value of Ratio.
c) Key element is -0.112 located at (S11, X4).
d) X4 is entering variable while S11 is departing variable.
e) Filling in the elements:

,CBi,Basic Variable,X1,X2,X3,X4,X5,X7,S1,S2,...,S4,S5,S6,S7,S8,S9,S10,S11,S12,Solution
0,NaN,Cj,-135.5611,-0.1287,0.058600,-0.0937,8.453800,35.256000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,NaN
1,-135.5611,X1,1.0000,0.0000,0.000000,0.0000,0.000000,0.000000,1.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.980000
2,0.0000,S2,0.0000,0.0000,0.763393,0.0000,37.232143,182.482143,578.333929,1.0,...,0.441071,0.0,0.0,0.0,0.0,0.0,0.0,-8.928571,0.0,616.439125
3,0.0000,S3,0.0000,0.0000,0.000000,0.0000,1.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,3.500000
4,-0.1287,X2,-0.0000,1.0000,-0.763393,0.0000,-37.232143,-182.482143,-578.333929,-0.0,...,-0.441071,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,8.928571,-0.0,192.060875
5,0.0000,S5,0.0000,0.0000,-1.236607,0.0000,37.232143,182.482143,578.333929,0.0,...,-0.558929,1.0,0.0,0.0,0.0,0.0,0.0,-8.928571,0.0,-155.310875
6,0.0000,S6,0.0000,0.0000,0.017479,0.0000,-0.173371,5.328029,-6.939634,0.0,...,0.004394,0.0,1.0,0.0,0.0,0.0,0.0,0.014286,0.0,9.511458
7,0.0000,S7,0.0000,0.0000,-0.017479,0.0000,0.173371,-5.328029,6.939634,0.0,...,-0.004394,0.0,0.0,1.0,0.0,0.0,0.0,-0.014286,0.0,-4.191458
8,0.0000,S8,0.0000,0.0000,-0.236607,0.0000,37.232143,182.482143,578.333929,0.0,...,-0.558929,0.0,0.0,0.0,-1.0,0.0,0.0,-8.928571,0.0,101.939125
9,0.0000,S9,0.0000,0.0000,0.000000,0.0000,1.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,1.0,0.0,0.000000,0.0,7.000000
10,0.0000,S10,0.0000,0.0000,0.000000,0.0000,0.000000,1.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.000000,0.0,0.400000
11,-0.0937,X4,-0.0000,-0.0000,0.236607,1.0000,-37.232143,-182.482143,-578.333929,-0.0,...,0.558929,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,8.928571,-0.0,8.310875
12,0.0000,S12,0.0000,0.0000,-0.017479,0.0000,0.173371,-5.328029,6.939634,0.0,...,-0.004394,0.0,0.0,0.0,0.0,0.0,0.0,0.985714,-1.0,-6.851458
13,NaN,Zj,-135.5611,-0.1287,0.076079,-0.0937,8.280429,40.584029,-6.939634,0.0,...,0.004394,0.0,0.0,0.0,0.0,0.0,0.0,-1.985714,0.0,NaN
14,NaN,Cj - Zj,0.0000,0.0000,-0.017479,0.0000,0.173371,-5.328029,6.939634,0.0,...,-0.004394,0.0,0.0,0.0,0.0,0.0,0.0,1.985714,0.0,NaN

Any of [0.0, 0.0, -0.01747857, 0.0, 0.17337143, -5.32802857, 6.93963429, 0.0, 0.0, -0.00439429, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.98571429, 0.0] is not >= 0, optimal solution is not found yet.
Proceed to next step.

Iteration 4:
a) Key column is X7 because -5.32802857 is the smallest value of Cj - Zj.
b)

,CBi,Basic Variable,X1,X2,X3,X4,X5,X7,S1,S2,...,S5,S6,S7,S8,S9,S10,S11,S12,Solution,Ratio
0,NaN,Cj,-135.5611,-0.1287,0.058600,-0.0937,8.453800,35.256000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,NaN,NaN
1,-135.5611,X1,1.0000,0.0000,0.000000,0.0000,0.000000,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.980000,NaN
2,0.0000,S2,0.0000,0.0000,0.763393,0.0000,37.232143,182.482143,578.333929,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-8.928571,0.0,616.439125,3.378079
3,0.0000,S3,0.0000,0.0000,0.000000,0.0000,1.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,3.500000,NaN
4,-0.1287,X2,-0.0000,1.0000,-0.763393,0.0000,-37.232143,-182.482143,-578.333929,-0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,8.928571,-0.0,192.060875,-1.052491
5,0.0000,S5,0.0000,0.0000,-1.236607,0.0000,37.232143,182.482143,578.333929,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,-8.928571,0.0,-155.310875,-0.851102
6,0.0000,S6,0.0000,0.0000,0.017479,0.0000,-0.173371,5.328029,-6.939634,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.014286,0.0,9.511458,1.785174
7,0.0000,S7,0.0000,0.0000,-0.017479,0.0000,0.173371,-5.328029,6.939634,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,-0.014286,0.0,-4.191458,0.786681
8,0.0000,S8,0.0000,0.0000,-0.236607,0.0000,37.232143,182.482143,578.333929,0.0,...,0.0,0.0,0.0,-1.0,0.0,0.0,-8.928571,0.0,101.939125,0.558625
9,0.0000,S9,0.0000,0.0000,0.000000,0.0000,1.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.000000,0.0,7.000000,NaN
10,0.0000,S10,0.0000,0.0000,0.000000,0.0000,0.000000,1.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.000000,0.0,0.400000,0.400000
11,-0.0937,X4,-0.0000,-0.0000,0.236607,1.0000,-37.232143,-182.482143,-578.333929,-0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,8.928571,-0.0,8.310875,-0.045544
12,0.0000,S12,0.0000,0.0000,-0.017479,0.0000,0.173371,-5.328029,6.939634,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.985714,-1.0,-6.851458,1.285927
13,NaN,Zj,-135.5611,-0.1287,0.076079,-0.0937,8.280429,40.584029,-6.939634,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-1.985714,0.0,NaN,NaN
14,NaN,Cj - Zj,0.0000,0.0000,-0.017479,0.0000,0.173371,-5.328029,6.939634,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.985714,0.0,NaN,NaN

Key row is S10 because 0.4 is the smallest non-negative value of Ratio.
c) Key element is 1.0 located at (S10, X7).
d) X7 is entering variable while S10 is departing variable.
e) Filling in the elements:

,CBi,Basic Variable,X1,X2,X3,X4,X5,X7,S1,S2,...,S4,S5,S6,S7,S8,S9,S10,S11,S12,Solution
0,NaN,Cj,-135.5611,-0.1287,0.058600,-0.0937,8.453800,35.256,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,NaN
1,-135.5611,X1,1.0000,0.0000,0.000000,0.0000,0.000000,0.000,1.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.980000
2,0.0000,S2,0.0000,0.0000,0.763393,0.0000,37.232143,0.000,578.333929,1.0,...,0.441071,0.0,0.0,0.0,0.0,0.0,-182.482143,-8.928571,0.0,543.446268
3,0.0000,S3,0.0000,0.0000,0.000000,0.0000,1.000000,0.000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,3.500000
4,-0.1287,X2,0.0000,1.0000,-0.763393,0.0000,-37.232143,0.000,-578.333929,0.0,...,-0.441071,0.0,0.0,0.0,0.0,0.0,182.482143,8.928571,0.0,265.053732
5,0.0000,S5,0.0000,0.0000,-1.236607,0.0000,37.232143,0.000,578.333929,0.0,...,-0.558929,1.0,0.0,0.0,0.0,0.0,-182.482143,-8.928571,0.0,-228.303732
6,0.0000,S6,0.0000,0.0000,0.017479,0.0000,-0.173371,0.000,-6.939634,0.0,...,0.004394,0.0,1.0,0.0,0.0,0.0,-5.328029,0.014286,0.0,7.380247
7,0.0000,S7,0.0000,0.0000,-0.017479,0.0000,0.173371,0.000,6.939634,0.0,...,-0.004394,0.0,0.0,1.0,0.0,0.0,5.328029,-0.014286,0.0,-2.060247
8,0.0000,S8,0.0000,0.0000,-0.236607,0.0000,37.232143,0.000,578.333929,0.0,...,-0.558929,0.0,0.0,0.0,-1.0,0.0,-182.482143,-8.928571,0.0,28.946268
9,0.0000,S9,0.0000,0.0000,0.000000,0.0000,1.000000,0.000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,1.0,0.000000,0.000000,0.0,7.000000
10,35.2560,X7,0.0000,0.0000,0.000000,0.0000,0.000000,1.000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,1.000000,0.000000,0.0,0.400000
11,-0.0937,X4,0.0000,0.0000,0.236607,1.0000,-37.232143,0.000,-578.333929,0.0,...,0.558929,0.0,0.0,0.0,0.0,0.0,182.482143,8.928571,0.0,81.303732
12,0.0000,S12,0.0000,0.0000,-0.017479,0.0000,0.173371,0.000,6.939634,0.0,...,-0.004394,0.0,0.0,0.0,0.0,0.0,5.328029,0.985714,-1.0,-4.720247
13,NaN,Zj,-135.5611,-0.1287,0.076079,-0.0937,8.280429,35.256,-6.939634,0.0,...,0.004394,0.0,0.0,0.0,0.0,0.0,-5.328029,-1.985714,0.0,NaN
14,NaN,Cj - Zj,0.0000,0.0000,-0.017479,0.0000,0.173371,0.000,6.939634,0.0,...,-0.004394,0.0,0.0,0.0,0.0,0.0,5.328029,1.985714,0.0,NaN

Any of [0.0, 0.0, -0.01747857, 0.0, 0.17337143, 0.0, 6.93963429, 0.0, 0.0, -0.00439429, 0.0, 0.0, 0.0, 0.0, 0.0, 5.32802857, 1.98571429, 0.0] is not >= 0, optimal solution is not found yet.
Proceed to next step.

Iteration 5:
a) Key column is X3 because -0.01747857 is the smallest value of Cj - Zj.
b)

,CBi,Basic Variable,X1,X2,X3,X4,X5,X7,S1,S2,...,S5,S6,S7,S8,S9,S10,S11,S12,Solution,Ratio
0,NaN,Cj,-135.5611,-0.1287,0.058600,-0.0937,8.453800,35.256,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,NaN,NaN
1,-135.5611,X1,1.0000,0.0000,0.000000,0.0000,0.000000,0.000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.980000,NaN
2,0.0000,S2,0.0000,0.0000,0.763393,0.0000,37.232143,0.000,578.333929,1.0,...,0.0,0.0,0.0,0.0,0.0,-182.482143,-8.928571,0.0,543.446268,711.882828
3,0.0000,S3,0.0000,0.0000,0.000000,0.0000,1.000000,0.000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,3.500000,NaN
4,-0.1287,X2,0.0000,1.0000,-0.763393,0.0000,-37.232143,0.000,-578.333929,0.0,...,0.0,0.0,0.0,0.0,0.0,182.482143,8.928571,0.0,265.053732,-347.204888
5,0.0000,S5,0.0000,0.0000,-1.236607,0.0000,37.232143,0.000,578.333929,0.0,...,1.0,0.0,0.0,0.0,0.0,-182.482143,-8.928571,0.0,-228.303732,184.621069
6,0.0000,S6,0.0000,0.0000,0.017479,0.0000,-0.173371,0.000,-6.939634,0.0,...,0.0,1.0,0.0,0.0,0.0,-5.328029,0.014286,0.0,7.380247,422.245468
7,0.0000,S7,0.0000,0.0000,-0.017479,0.0000,0.173371,0.000,6.939634,0.0,...,0.0,0.0,1.0,0.0,0.0,5.328029,-0.014286,0.0,-2.060247,117.872742
8,0.0000,S8,0.0000,0.0000,-0.236607,0.0000,37.232143,0.000,578.333929,0.0,...,0.0,0.0,0.0,-1.0,0.0,-182.482143,-8.928571,0.0,28.946268,-122.338945
9,0.0000,S9,0.0000,0.0000,0.000000,0.0000,1.000000,0.000,0.000000,0.0,...,0.0,0.0,0.0,0.0,1.0,0.000000,0.000000,0.0,7.000000,NaN
10,35.2560,X7,0.0000,0.0000,0.000000,0.0000,0.000000,1.000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,1.000000,0.000000,0.0,0.400000,NaN
11,-0.0937,X4,0.0000,0.0000,0.236607,1.0000,-37.232143,0.000,-578.333929,0.0,...,0.0,0.0,0.0,0.0,0.0,182.482143,8.928571,0.0,81.303732,343.623325
12,0.0000,S12,0.0000,0.0000,-0.017479,0.0000,0.173371,0.000,6.939634,0.0,...,0.0,0.0,0.0,0.0,0.0,5.328029,0.985714,-1.0,-4.720247,270.059105
13,NaN,Zj,-135.5611,-0.1287,0.076079,-0.0937,8.280429,35.256,-6.939634,0.0,...,0.0,0.0,0.0,0.0,0.0,-5.328029,-1.985714,0.0,NaN,NaN
14,NaN,Cj - Zj,0.0000,0.0000,-0.017479,0.0000,0.173371,0.000,6.939634,0.0,...,0.0,0.0,0.0,0.0,0.0,5.328029,1.985714,0.0,NaN,NaN

Key row is S7 because 117.87274188 is the smallest non-negative value of Ratio.
c) Key element is -0.01747857 located at (S7, X3).
d) X3 is entering variable while S7 is departing variable.
e) Filling in the elements:

,CBi,Basic Variable,X1,X2,X3,X4,X5,X7,S1,S2,...,S4,S5,S6,S7,S8,S9,S10,S11,S12,Solution
0,NaN,Cj,-135.5611,-0.1287,0.0586,-0.0937,8.453800e+00,35.256,0.000000e+00,0.0,...,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000e+00,0.000000,0.0,NaN
1,-135.5611,X1,1.0000,0.0000,0.0000,0.0000,0.000000e+00,0.000,1.000000e+00,0.0,...,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000e+00,0.000000,0.0,0.980000
2,0.0000,S2,0.0000,0.0000,0.0000,0.0000,4.480430e+01,0.000,8.814289e+02,1.0,...,0.249147,0.0,0.0,43.675933,0.0,0.0,5.022448e+01,-9.552513,0.0,453.463058
3,0.0000,S3,0.0000,0.0000,0.0000,0.0000,1.000000e+00,0.000,0.000000e+00,0.0,...,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000e+00,0.000000,0.0,3.500000
4,-0.1287,X2,0.0000,1.0000,0.0000,0.0000,-4.480430e+01,0.000,-8.814289e+02,0.0,...,-0.249147,0.0,0.0,-43.675933,0.0,0.0,-5.022448e+01,9.552513,0.0,355.036942
5,0.0000,S5,0.0000,0.0000,0.0000,0.0000,2.496613e+01,0.000,8.735547e+01,0.0,...,-0.248033,1.0,0.0,-70.749903,0.0,0.0,-5.594396e+02,-7.917859,0.0,-82.541458
6,0.0000,S6,0.0000,0.0000,0.0000,0.0000,0.000000e+00,0.000,0.000000e+00,0.0,...,0.000000,0.0,1.0,1.000000,0.0,0.0,0.000000e+00,0.000000,0.0,5.320000
7,0.0586,X3,-0.0000,-0.0000,1.0000,-0.0000,-9.919085e+00,-0.000,-3.970367e+02,-0.0,...,0.251410,-0.0,-0.0,-57.212918,-0.0,-0.0,-3.048321e+02,0.817327,-0.0,117.872742
8,0.0000,S8,0.0000,0.0000,0.0000,0.0000,3.488522e+01,0.000,4.843922e+02,0.0,...,-0.499443,0.0,0.0,-13.536985,-1.0,0.0,-2.546076e+02,-8.735186,0.0,56.835800
9,0.0000,S9,0.0000,0.0000,0.0000,0.0000,1.000000e+00,0.000,0.000000e+00,0.0,...,0.000000,0.0,0.0,0.000000,0.0,1.0,0.000000e+00,0.000000,0.0,7.000000
10,35.2560,X7,0.0000,0.0000,0.0000,0.0000,0.000000e+00,1.000,0.000000e+00,0.0,...,0.000000,0.0,0.0,0.000000,0.0,0.0,1.000000e+00,0.000000,0.0,0.400000
11,-0.0937,X4,0.0000,0.0000,0.0000,1.0000,-3.488522e+01,0.000,-4.843922e+02,0.0,...,0.499443,0.0,0.0,13.536985,0.0,0.0,2.546076e+02,8.735186,0.0,53.414200
12,0.0000,S12,0.0000,0.0000,0.0000,0.0000,0.000000e+00,0.000,0.000000e+00,0.0,...,0.000000,0.0,0.0,-1.000000,0.0,0.0,0.000000e+00,1.000000,-1.0,-2.660000
13,NaN,Zj,-135.5611,-0.1287,0.0586,-0.0937,8.453800e+00,35.256,8.200000e-07,0.0,...,-0.000000,0.0,0.0,1.000000,0.0,0.0,6.300000e-07,-2.000000,0.0,NaN
14,NaN,Cj - Zj,0.0000,0.0000,0.0000,0.0000,-2.000000e-08,0.000,-8.200000e-07,0.0,...,0.000000,0.0,0.0,-1.000000,0.0,0.0,-6.300000e-07,2.000000,0.0,NaN

Any of [0.0, 0.0, 0.0, 0.0, -2e-08, 0.0, -8.2e-07, 0.0, 0.0, 0.0, 0.0, 0.0, -1.00000012, 0.0, 0.0, -6.3e-07, 2.0, 0.0] is not >= 0, optimal solution is not found yet.
Proceed to next step.

Iteration 6:
a) Key column is S7 because -1.00000012 is the smallest value of Cj - Zj.
b)

,CBi,Basic Variable,X1,X2,X3,X4,X5,X7,S1,S2,...,S5,S6,S7,S8,S9,S10,S11,S12,Solution,Ratio
0,NaN,Cj,-135.5611,-0.1287,0.0586,-0.0937,8.453800e+00,35.256,0.000000e+00,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.000000e+00,0.000000,0.0,NaN,NaN
1,-135.5611,X1,1.0000,0.0000,0.0000,0.0000,0.000000e+00,0.000,1.000000e+00,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.000000e+00,0.000000,0.0,0.980000,NaN
2,0.0000,S2,0.0000,0.0000,0.0000,0.0000,4.480430e+01,0.000,8.814289e+02,1.0,...,0.0,0.0,43.675933,0.0,0.0,5.022448e+01,-9.552513,0.0,453.463058,10.382447
3,0.0000,S3,0.0000,0.0000,0.0000,0.0000,1.000000e+00,0.000,0.000000e+00,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.000000e+00,0.000000,0.0,3.500000,NaN
4,-0.1287,X2,0.0000,1.0000,0.0000,0.0000,-4.480430e+01,0.000,-8.814289e+02,0.0,...,0.0,0.0,-43.675933,0.0,0.0,-5.022448e+01,9.552513,0.0,355.036942,-8.128892
5,0.0000,S5,0.0000,0.0000,0.0000,0.0000,2.496613e+01,0.000,8.735547e+01,0.0,...,1.0,0.0,-70.749903,0.0,0.0,-5.594396e+02,-7.917859,0.0,-82.541458,1.166665
6,0.0000,S6,0.0000,0.0000,0.0000,0.0000,0.000000e+00,0.000,0.000000e+00,0.0,...,0.0,1.0,1.000000,0.0,0.0,0.000000e+00,0.000000,0.0,5.320000,5.320000
7,0.0586,X3,-0.0000,-0.0000,1.0000,-0.0000,-9.919085e+00,-0.000,-3.970367e+02,-0.0,...,-0.0,-0.0,-57.212918,-0.0,-0.0,-3.048321e+02,0.817327,-0.0,117.872742,-2.060247
8,0.0000,S8,0.0000,0.0000,0.0000,0.0000,3.488522e+01,0.000,4.843922e+02,0.0,...,0.0,0.0,-13.536985,-1.0,0.0,-2.546076e+02,-8.735186,0.0,56.835800,-4.198557
9,0.0000,S9,0.0000,0.0000,0.0000,0.0000,1.000000e+00,0.000,0.000000e+00,0.0,...,0.0,0.0,0.000000,0.0,1.0,0.000000e+00,0.000000,0.0,7.000000,NaN
10,35.2560,X7,0.0000,0.0000,0.0000,0.0000,0.000000e+00,1.000,0.000000e+00,0.0,...,0.0,0.0,0.000000,0.0,0.0,1.000000e+00,0.000000,0.0,0.400000,NaN
11,-0.0937,X4,0.0000,0.0000,0.0000,1.0000,-3.488522e+01,0.000,-4.843922e+02,0.0,...,0.0,0.0,13.536985,0.0,0.0,2.546076e+02,8.735186,0.0,53.414200,3.945797
12,0.0000,S12,0.0000,0.0000,0.0000,0.0000,0.000000e+00,0.000,0.000000e+00,0.0,...,0.0,0.0,-1.000000,0.0,0.0,0.000000e+00,1.000000,-1.0,-2.660000,2.660000
13,NaN,Zj,-135.5611,-0.1287,0.0586,-0.0937,8.453800e+00,35.256,8.200000e-07,0.0,...,0.0,0.0,1.000000,0.0,0.0,6.300000e-07,-2.000000,0.0,NaN,NaN
14,NaN,Cj - Zj,0.0000,0.0000,0.0000,0.0000,-2.000000e-08,0.000,-8.200000e-07,0.0,...,0.0,0.0,-1.000000,0.0,0.0,-6.300000e-07,2.000000,0.0,NaN,NaN

Key row is S5 because 1.16666531 is the smallest non-negative value of Ratio.
c) Key element is -70.74990345 located at (S5, S7).
d) S7 is entering variable while S5 is departing variable.
e) Filling in the elements:

,CBi,Basic Variable,X1,X2,X3,X4,X5,X7,S1,S2,...,S4,S5,S6,S7,S8,S9,S10,S11,S12,Solution
0,NaN,Cj,-135.5611,-0.1287,0.0586,-0.0937,8.453800,35.256,0.000000,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,NaN
1,-135.5611,X1,1.0000,0.0000,0.0000,0.0000,0.000000,0.000,1.000000,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.980000
2,0.0000,S2,0.0000,0.0000,0.0000,0.0000,60.216607,0.000,935.355959,1.0,...,0.096029,0.617329,0.0,0.0,0.0,0.0,-295.133575,-14.440433,0.0,402.507862
3,0.0000,S3,0.0000,0.0000,0.0000,0.0000,1.000000,0.000,0.000000,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,3.500000
4,-0.1287,X2,0.0000,1.0000,0.0000,0.0000,-60.216607,0.000,-935.355959,0.0,...,-0.096029,-0.617329,0.0,0.0,0.0,0.0,295.133575,14.440433,0.0,405.992138
5,0.0000,S7,-0.0000,-0.0000,-0.0000,-0.0000,-0.352879,-0.000,-1.234708,-0.0,...,0.003506,-0.014134,-0.0,1.0,-0.0,-0.0,7.907285,0.111913,-0.0,1.166665
6,0.0000,S6,0.0000,0.0000,0.0000,0.0000,0.352879,0.000,1.234708,0.0,...,-0.003506,0.014134,1.0,0.0,0.0,0.0,-7.907285,-0.111913,0.0,4.153335
7,0.0586,X3,-0.0000,-0.0000,1.0000,-0.0000,-30.108303,-0.000,-467.677979,-0.0,...,0.451986,-0.808664,-0.0,0.0,-0.0,-0.0,147.566787,7.220217,-0.0,184.621069
8,0.0000,S8,0.0000,0.0000,0.0000,0.0000,30.108303,0.000,467.677979,0.0,...,-0.451986,-0.191336,0.0,0.0,-1.0,0.0,-147.566787,-7.220217,0.0,72.628931
9,0.0000,S9,0.0000,0.0000,0.0000,0.0000,1.000000,0.000,0.000000,0.0,...,0.000000,0.000000,0.0,0.0,0.0,1.0,0.000000,0.000000,0.0,7.000000
10,35.2560,X7,0.0000,0.0000,0.0000,0.0000,0.000000,1.000,0.000000,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,1.000000,0.000000,0.0,0.400000
11,-0.0937,X4,0.0000,0.0000,0.0000,1.0000,-30.108303,0.000,-467.677979,0.0,...,0.451986,0.191336,0.0,0.0,0.0,0.0,147.566787,7.220217,0.0,37.621069
12,0.0000,S12,0.0000,0.0000,0.0000,0.0000,-0.352879,0.000,-1.234708,0.0,...,0.003506,-0.014134,0.0,0.0,0.0,0.0,7.907285,1.111913,-1.0,-1.493335
13,NaN,Zj,-135.5611,-0.1287,0.0586,-0.0937,8.806679,35.256,1.234709,0.0,...,-0.003506,0.014134,0.0,0.0,0.0,0.0,-7.907285,-2.111913,0.0,NaN
14,NaN,Cj - Zj,0.0000,0.0000,0.0000,0.0000,-0.352879,0.000,-1.234709,0.0,...,0.003506,-0.014134,0.0,0.0,0.0,0.0,7.907285,2.111913,0.0,NaN

Any of [0.0, 0.0, 0.0, 0.0, -0.35287872, 0.0, -1.23470898, 0.0, 0.0, 0.00350578, -0.0141343, 0.0, 0.0, 0.0, 0.0, 7.90728529, 2.11191336, 0.0] is not >= 0, optimal solution is not found yet.
Proceed to next step.

Iteration 7:
a) Key column is S1 because -1.23470898 is the smallest value of Cj - Zj.
b)

,CBi,Basic Variable,X1,X2,X3,X4,X5,X7,S1,S2,...,S5,S6,S7,S8,S9,S10,S11,S12,Solution,Ratio
0,NaN,Cj,-135.5611,-0.1287,0.0586,-0.0937,8.453800,35.256,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,NaN,NaN
1,-135.5611,X1,1.0000,0.0000,0.0000,0.0000,0.000000,0.000,1.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.980000,0.980000
2,0.0000,S2,0.0000,0.0000,0.0000,0.0000,60.216607,0.000,935.355959,1.0,...,0.617329,0.0,0.0,0.0,0.0,-295.133575,-14.440433,0.0,402.507862,0.430326
3,0.0000,S3,0.0000,0.0000,0.0000,0.0000,1.000000,0.000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,3.500000,NaN
4,-0.1287,X2,0.0000,1.0000,0.0000,0.0000,-60.216607,0.000,-935.355959,0.0,...,-0.617329,0.0,0.0,0.0,0.0,295.133575,14.440433,0.0,405.992138,-0.434051
5,0.0000,S7,-0.0000,-0.0000,-0.0000,-0.0000,-0.352879,-0.000,-1.234708,-0.0,...,-0.014134,-0.0,1.0,-0.0,-0.0,7.907285,0.111913,-0.0,1.166665,-0.944892
6,0.0000,S6,0.0000,0.0000,0.0000,0.0000,0.352879,0.000,1.234708,0.0,...,0.014134,1.0,0.0,0.0,0.0,-7.907285,-0.111913,0.0,4.153335,3.363819
7,0.0586,X3,-0.0000,-0.0000,1.0000,-0.0000,-30.108303,-0.000,-467.677979,-0.0,...,-0.808664,-0.0,0.0,-0.0,-0.0,147.566787,7.220217,-0.0,184.621069,-0.394761
8,0.0000,S8,0.0000,0.0000,0.0000,0.0000,30.108303,0.000,467.677979,0.0,...,-0.191336,0.0,0.0,-1.0,0.0,-147.566787,-7.220217,0.0,72.628931,0.155297
9,0.0000,S9,0.0000,0.0000,0.0000,0.0000,1.000000,0.000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,1.0,0.000000,0.000000,0.0,7.000000,NaN
10,35.2560,X7,0.0000,0.0000,0.0000,0.0000,0.000000,1.000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,1.000000,0.000000,0.0,0.400000,NaN
11,-0.0937,X4,0.0000,0.0000,0.0000,1.0000,-30.108303,0.000,-467.677979,0.0,...,0.191336,0.0,0.0,0.0,0.0,147.566787,7.220217,0.0,37.621069,-0.080442
12,0.0000,S12,0.0000,0.0000,0.0000,0.0000,-0.352879,0.000,-1.234708,0.0,...,-0.014134,0.0,0.0,0.0,0.0,7.907285,1.111913,-1.0,-1.493335,1.209464
13,NaN,Zj,-135.5611,-0.1287,0.0586,-0.0937,8.806679,35.256,1.234709,0.0,...,0.014134,0.0,0.0,0.0,0.0,-7.907285,-2.111913,0.0,NaN,NaN
14,NaN,Cj - Zj,0.0000,0.0000,0.0000,0.0000,-0.352879,0.000,-1.234709,0.0,...,-0.014134,0.0,0.0,0.0,0.0,7.907285,2.111913,0.0,NaN,NaN

Key row is S8 because 0.15529688 is the smallest non-negative value of Ratio.
c) Key element is 467.67797942 located at (S8, S1).
d) S1 is entering variable while S8 is departing variable.
e) Filling in the elements:

,CBi,Basic Variable,X1,X2,X3,X4,X5,X7,S1,S2,...,S4,S5,S6,S7,S8,S9,S10,S11,S12,Solution
0,NaN,Cj,-135.5611,-0.1287,0.0586,-0.0937,8.453800e+00,35.256,0.0,0.0,...,0.000000e+00,0.000000,0.0,0.0,0.000000,0.0,0.000000e+00,0.000000e+00,0.0,NaN
1,-135.5611,X1,1.0000,0.0000,0.0000,0.0000,-6.437828e-02,0.000,0.0,0.0,...,9.664500e-04,0.000409,0.0,0.0,0.002138,0.0,3.155308e-01,1.543844e-02,0.0,0.824703
2,0.0000,S2,0.0000,0.0000,0.0000,0.0000,1.000000e-08,0.000,0.0,1.0,...,1.000000e+00,1.000000,0.0,0.0,2.000000,0.0,-6.000000e-08,1.000000e-08,0.0,257.250000
3,0.0000,S3,0.0000,0.0000,0.0000,0.0000,1.000000e+00,0.000,0.0,0.0,...,0.000000e+00,0.000000,0.0,0.0,0.000000,0.0,0.000000e+00,0.000000e+00,0.0,3.500000
4,-0.1287,X2,0.0000,1.0000,0.0000,0.0000,-1.000000e-08,0.000,0.0,0.0,...,-1.000000e+00,-1.000000,0.0,0.0,-2.000000,0.0,6.000000e-08,-1.000000e-08,0.0,551.250000
5,0.0000,S7,0.0000,0.0000,0.0000,0.0000,-2.733903e-01,0.000,0.0,0.0,...,2.312490e-03,-0.014639,0.0,1.0,-0.002640,0.0,7.517697e+00,9.285139e-02,0.0,1.358412
6,0.0000,S6,0.0000,0.0000,0.0000,0.0000,2.733903e-01,0.000,0.0,0.0,...,-2.312490e-03,0.014639,1.0,0.0,0.002640,0.0,-7.517697e+00,-9.285139e-02,0.0,3.961588
7,0.0586,X3,0.0000,0.0000,1.0000,0.0000,-1.000000e-08,0.000,0.0,0.0,...,1.000000e-08,-1.000000,0.0,0.0,-1.000000,0.0,7.000000e-08,0.000000e+00,0.0,257.250000
8,0.0000,S1,0.0000,0.0000,0.0000,0.0000,6.437828e-02,0.000,1.0,0.0,...,-9.664500e-04,-0.000409,0.0,0.0,-0.002138,0.0,-3.155308e-01,-1.543844e-02,0.0,0.155297
9,0.0000,S9,0.0000,0.0000,0.0000,0.0000,1.000000e+00,0.000,0.0,0.0,...,0.000000e+00,0.000000,0.0,0.0,0.000000,1.0,0.000000e+00,0.000000e+00,0.0,7.000000
10,35.2560,X7,0.0000,0.0000,0.0000,0.0000,0.000000e+00,1.000,0.0,0.0,...,0.000000e+00,0.000000,0.0,0.0,0.000000,0.0,1.000000e+00,0.000000e+00,0.0,0.400000
11,-0.0937,X4,0.0000,0.0000,0.0000,1.0000,0.000000e+00,0.000,0.0,0.0,...,0.000000e+00,0.000000,0.0,0.0,-1.000000,0.0,0.000000e+00,0.000000e+00,0.0,110.250000
12,0.0000,S12,0.0000,0.0000,0.0000,0.0000,-2.733903e-01,0.000,0.0,0.0,...,2.312490e-03,-0.014639,0.0,0.0,-0.002640,0.0,7.517697e+00,1.092851e+00,-1.0,-1.301588
13,NaN,Zj,-135.5611,-0.1287,0.0586,-0.0937,8.727190e+00,35.256,0.0,0.0,...,-2.313020e-03,0.014639,0.0,0.0,0.002641,0.0,-7.517697e+00,-2.092852e+00,0.0,NaN
14,NaN,Cj - Zj,0.0000,0.0000,0.0000,0.0000,-2.733905e-01,0.000,0.0,0.0,...,2.313020e-03,-0.014639,0.0,0.0,-0.002641,0.0,7.517697e+00,2.092852e+00,0.0,NaN

Any of [0.0, 0.0, 0.0, 0.0, -0.27339045, 0.0, 0.0, 0.0, 0.0, 0.00231302, -0.01463924, 0.0, 0.0, -0.00264054, 0.0, 7.51769691, 2.09285191, 0.0] is not >= 0, optimal solution is not found yet.
Proceed to next step.

Iteration 8:
a) Key column is X5 because -0.27339045 is the smallest value of Cj - Zj.
b)

,CBi,Basic Variable,X1,X2,X3,X4,X5,X7,S1,S2,...,S5,S6,S7,S8,S9,S10,S11,S12,Solution,Ratio
0,NaN,Cj,-135.5611,-0.1287,0.0586,-0.0937,8.453800e+00,35.256,0.0,0.0,...,0.000000,0.0,0.0,0.000000,0.0,0.000000e+00,0.000000e+00,0.0,NaN,NaN
1,-135.5611,X1,1.0000,0.0000,0.0000,0.0000,-6.437828e-02,0.000,0.0,0.0,...,0.000409,0.0,0.0,0.002138,0.0,3.155308e-01,1.543844e-02,0.0,0.824703,-1.281027e+01
2,0.0000,S2,0.0000,0.0000,0.0000,0.0000,1.000000e-08,0.000,0.0,1.0,...,1.000000,0.0,0.0,2.000000,0.0,-6.000000e-08,1.000000e-08,0.0,257.250000,2.572500e+10
3,0.0000,S3,0.0000,0.0000,0.0000,0.0000,1.000000e+00,0.000,0.0,0.0,...,0.000000,0.0,0.0,0.000000,0.0,0.000000e+00,0.000000e+00,0.0,3.500000,3.500000e+00
4,-0.1287,X2,0.0000,1.0000,0.0000,0.0000,-1.000000e-08,0.000,0.0,0.0,...,-1.000000,0.0,0.0,-2.000000,0.0,6.000000e-08,-1.000000e-08,0.0,551.250000,-5.512500e+10
5,0.0000,S7,0.0000,0.0000,0.0000,0.0000,-2.733903e-01,0.000,0.0,0.0,...,-0.014639,0.0,1.0,-0.002640,0.0,7.517697e+00,9.285139e-02,0.0,1.358412,-4.968763e+00
6,0.0000,S6,0.0000,0.0000,0.0000,0.0000,2.733903e-01,0.000,0.0,0.0,...,0.014639,1.0,0.0,0.002640,0.0,-7.517697e+00,-9.285139e-02,0.0,3.961588,1.449060e+01
7,0.0586,X3,0.0000,0.0000,1.0000,0.0000,-1.000000e-08,0.000,0.0,0.0,...,-1.000000,0.0,0.0,-1.000000,0.0,7.000000e-08,0.000000e+00,0.0,257.250000,-2.572500e+10
8,0.0000,S1,0.0000,0.0000,0.0000,0.0000,6.437828e-02,0.000,1.0,0.0,...,-0.000409,0.0,0.0,-0.002138,0.0,-3.155308e-01,-1.543844e-02,0.0,0.155297,2.412256e+00
9,0.0000,S9,0.0000,0.0000,0.0000,0.0000,1.000000e+00,0.000,0.0,0.0,...,0.000000,0.0,0.0,0.000000,1.0,0.000000e+00,0.000000e+00,0.0,7.000000,7.000000e+00
10,35.2560,X7,0.0000,0.0000,0.0000,0.0000,0.000000e+00,1.000,0.0,0.0,...,0.000000,0.0,0.0,0.000000,0.0,1.000000e+00,0.000000e+00,0.0,0.400000,NaN
11,-0.0937,X4,0.0000,0.0000,0.0000,1.0000,0.000000e+00,0.000,0.0,0.0,...,0.000000,0.0,0.0,-1.000000,0.0,0.000000e+00,0.000000e+00,0.0,110.250000,NaN
12,0.0000,S12,0.0000,0.0000,0.0000,0.0000,-2.733903e-01,0.000,0.0,0.0,...,-0.014639,0.0,0.0,-0.002640,0.0,7.517697e+00,1.092851e+00,-1.0,-1.301588,4.760917e+00
13,NaN,Zj,-135.5611,-0.1287,0.0586,-0.0937,8.727190e+00,35.256,0.0,0.0,...,0.014639,0.0,0.0,0.002641,0.0,-7.517697e+00,-2.092852e+00,0.0,NaN,NaN
14,NaN,Cj - Zj,0.0000,0.0000,0.0000,0.0000,-2.733905e-01,0.000,0.0,0.0,...,-0.014639,0.0,0.0,-0.002641,0.0,7.517697e+00,2.092852e+00,0.0,NaN,NaN

Key row is S1 because 2.41225581 is the smallest non-negative value of Ratio.
c) Key element is 0.06437828 located at (S1, X5).
d) X5 is entering variable while S1 is departing variable.
e) Filling in the elements:

,CBi,Basic Variable,X1,X2,X3,X4,X5,X7,S1,S2,...,S4,S5,S6,S7,S8,S9,S10,S11,S12,Solution
0,NaN,Cj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,0.000000e+00,0.0,...,0.000000e+00,0.000000,0.0,0.0,0.000000,0.0,0.000000e+00,0.000000e+00,0.0,NaN
1,-135.5611,X1,1.0000,0.0000,0.0000,0.0000,0.0000,0.000,1.000000e+00,0.0,...,0.000000e+00,0.000000,0.0,0.0,0.000000,0.0,0.000000e+00,-0.000000e+00,0.0,0.980000
2,0.0000,S2,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,-1.600000e-07,1.0,...,1.000000e+00,1.000000,0.0,0.0,2.000000,0.0,-1.000000e-08,1.000000e-08,0.0,257.250000
3,0.0000,S3,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,-1.553319e+01,0.0,...,1.501205e-02,0.006355,0.0,0.0,0.033213,0.0,4.901199e+00,2.398082e-01,0.0,1.087744
4,-0.1287,X2,0.0000,1.0000,0.0000,0.0000,0.0000,0.000,1.600000e-07,0.0,...,-1.000000e+00,-1.000000,0.0,0.0,-2.000000,0.0,1.000000e-08,-1.000000e-08,0.0,551.250000
5,0.0000,S7,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,4.246623e+00,0.0,...,-1.791660e-03,-0.016377,0.0,1.0,-0.011720,0.0,6.177756e+00,2.729016e-02,0.0,2.017899
6,0.0000,S6,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,-4.246623e+00,0.0,...,1.791660e-03,0.016377,1.0,0.0,0.011720,0.0,-6.177756e+00,-2.729016e-02,0.0,3.302101
7,0.0586,X3,0.0000,0.0000,1.0000,0.0000,0.0000,0.000,1.600000e-07,0.0,...,1.000000e-08,-1.000000,0.0,0.0,-1.000000,0.0,2.000000e-08,-0.000000e+00,0.0,257.250000
8,8.4538,X5,0.0000,0.0000,0.0000,0.0000,1.0000,0.000,1.553319e+01,0.0,...,-1.501205e-02,-0.006355,0.0,0.0,-0.033213,0.0,-4.901199e+00,-2.398082e-01,0.0,2.412256
9,0.0000,S9,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,-1.553319e+01,0.0,...,1.501205e-02,0.006355,0.0,0.0,0.033213,1.0,4.901199e+00,2.398082e-01,0.0,4.587744
10,35.2560,X7,0.0000,0.0000,0.0000,0.0000,0.0000,1.000,0.000000e+00,0.0,...,0.000000e+00,0.000000,0.0,0.0,0.000000,0.0,1.000000e+00,0.000000e+00,0.0,0.400000
11,-0.0937,X4,0.0000,0.0000,0.0000,1.0000,0.0000,0.000,0.000000e+00,0.0,...,0.000000e+00,0.000000,0.0,0.0,-1.000000,0.0,0.000000e+00,0.000000e+00,0.0,110.250000
12,0.0000,S12,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,4.246623e+00,0.0,...,-1.791660e-03,-0.016377,0.0,0.0,-0.011720,0.0,6.177756e+00,1.027290e+00,-1.0,-0.642101
13,NaN,Zj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,-4.246626e+00,0.0,...,1.791130e-03,0.016377,0.0,0.0,0.011721,0.0,-6.177756e+00,-2.027291e+00,0.0,NaN
14,NaN,Cj - Zj,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,4.246626e+00,0.0,...,-1.791130e-03,-0.016377,0.0,0.0,-0.011721,0.0,6.177756e+00,2.027291e+00,0.0,NaN

Any of [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.24662566, 0.0, 0.0, -0.00179113, -0.01637661, 0.0, 0.0, -0.01172073, 0.0, 6.17775594, 2.02729064, 0.0] is not >= 0, optimal solution is not found yet.
Proceed to next step.

Iteration 9:
a) Key column is S5 because -0.01637661 is the smallest value of Cj - Zj.
b)

,CBi,Basic Variable,X1,X2,X3,X4,X5,X7,S1,S2,...,S5,S6,S7,S8,S9,S10,S11,S12,Solution,Ratio
0,NaN,Cj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,0.000000e+00,0.0,...,0.000000,0.0,0.0,0.000000,0.0,0.000000e+00,0.000000e+00,0.0,NaN,NaN
1,-135.5611,X1,1.0000,0.0000,0.0000,0.0000,0.0000,0.000,1.000000e+00,0.0,...,0.000000,0.0,0.0,0.000000,0.0,0.000000e+00,-0.000000e+00,0.0,0.980000,NaN
2,0.0000,S2,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,-1.600000e-07,1.0,...,1.000000,0.0,0.0,2.000000,0.0,-1.000000e-08,1.000000e-08,0.0,257.250000,257.250000
3,0.0000,S3,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,-1.553319e+01,0.0,...,0.006355,0.0,0.0,0.033213,0.0,4.901199e+00,2.398082e-01,0.0,1.087744,171.165139
4,-0.1287,X2,0.0000,1.0000,0.0000,0.0000,0.0000,0.000,1.600000e-07,0.0,...,-1.000000,0.0,0.0,-2.000000,0.0,1.000000e-08,-1.000000e-08,0.0,551.250000,-551.250000
5,0.0000,S7,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,4.246623e+00,0.0,...,-0.016377,0.0,1.0,-0.011720,0.0,6.177756e+00,2.729016e-02,0.0,2.017899,-123.216847
6,0.0000,S6,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,-4.246623e+00,0.0,...,0.016377,1.0,0.0,0.011720,0.0,-6.177756e+00,-2.729016e-02,0.0,3.302101,201.632742
7,0.0586,X3,0.0000,0.0000,1.0000,0.0000,0.0000,0.000,1.600000e-07,0.0,...,-1.000000,0.0,0.0,-1.000000,0.0,2.000000e-08,-0.000000e+00,0.0,257.250000,-257.250000
8,8.4538,X5,0.0000,0.0000,0.0000,0.0000,1.0000,0.000,1.553319e+01,0.0,...,-0.006355,0.0,0.0,-0.033213,0.0,-4.901199e+00,-2.398082e-01,0.0,2.412256,-379.587504
9,0.0000,S9,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,-1.553319e+01,0.0,...,0.006355,0.0,0.0,0.033213,1.0,4.901199e+00,2.398082e-01,0.0,4.587744,721.917782
10,35.2560,X7,0.0000,0.0000,0.0000,0.0000,0.0000,1.000,0.000000e+00,0.0,...,0.000000,0.0,0.0,0.000000,0.0,1.000000e+00,0.000000e+00,0.0,0.400000,NaN
11,-0.0937,X4,0.0000,0.0000,0.0000,1.0000,0.0000,0.000,0.000000e+00,0.0,...,0.000000,0.0,0.0,-1.000000,0.0,0.000000e+00,0.000000e+00,0.0,110.250000,NaN
12,0.0000,S12,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,4.246623e+00,0.0,...,-0.016377,0.0,0.0,-0.011720,0.0,6.177756e+00,1.027290e+00,-1.0,-0.642101,39.207947
13,NaN,Zj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,-4.246626e+00,0.0,...,0.016377,0.0,0.0,0.011721,0.0,-6.177756e+00,-2.027291e+00,0.0,NaN,NaN
14,NaN,Cj - Zj,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,4.246626e+00,0.0,...,-0.016377,0.0,0.0,-0.011721,0.0,6.177756e+00,2.027291e+00,0.0,NaN,NaN

Key row is S12 because 39.20794709 is the smallest non-negative value of Ratio.
c) Key element is -0.01637681 located at (S12, S5).
d) S5 is entering variable while S12 is departing variable.
e) Filling in the elements:

,CBi,Basic Variable,X1,X2,X3,X4,X5,X7,S1,S2,...,S4,S5,S6,S7,S8,S9,S10,S11,S12,Solution
0,NaN,Cj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,0.000000,0.0,...,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.0,0.000000,0.000000,0.000000,NaN
1,-135.5611,X1,1.0000,0.0000,0.0000,0.0000,0.0000,0.000,1.000000,0.0,...,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.0,0.000000,0.000000,0.000000,0.980000
2,0.0000,S2,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,259.307089,1.0,...,8.905977e-01,0.0,0.0,0.0,1.284336e+00,0.0,377.225875,62.728343,-61.061953,218.042053
3,0.0000,S3,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,-13.885308,0.0,...,1.431681e-02,0.0,0.0,0.0,2.866538e-02,0.0,7.298447,0.638443,-0.388045,0.838580
4,-0.1287,X2,0.0000,1.0000,0.0000,0.0000,0.0000,0.000,-259.307089,0.0,...,-8.905977e-01,0.0,0.0,0.0,-1.284336e+00,0.0,-377.225875,-62.728343,61.061953,590.457947
5,0.0000,S7,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.000000,0.0,...,0.000000e+00,0.0,0.0,1.0,0.000000e+00,0.0,0.000000,-1.000000,1.000000,2.660000
6,0.0000,S6,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.000000,0.0,...,0.000000e+00,0.0,1.0,0.0,0.000000e+00,0.0,0.000000,1.000000,-1.000000,2.660000
7,0.0586,X3,0.0000,0.0000,1.0000,0.0000,0.0000,0.000,-259.307089,0.0,...,1.094023e-01,0.0,0.0,0.0,-2.843362e-01,0.0,-377.225875,-62.728343,61.061953,296.457947
8,8.4538,X5,0.0000,0.0000,0.0000,0.0000,1.0000,0.000,13.885308,0.0,...,-1.431681e-02,0.0,0.0,0.0,-2.866538e-02,0.0,-7.298447,-0.638443,0.388045,2.661420
9,0.0000,S9,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,-13.885308,0.0,...,1.431681e-02,0.0,0.0,0.0,2.866538e-02,1.0,7.298447,0.638443,-0.388045,4.338580
10,35.2560,X7,0.0000,0.0000,0.0000,0.0000,0.0000,1.000,0.000000,0.0,...,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.0,1.000000,0.000000,0.000000,0.400000
11,-0.0937,X4,0.0000,0.0000,0.0000,1.0000,0.0000,0.000,0.000000,0.0,...,0.000000e+00,0.0,0.0,0.0,-1.000000e+00,0.0,0.000000,0.000000,0.000000,110.250000
12,0.0000,S5,-0.0000,-0.0000,-0.0000,-0.0000,-0.0000,-0.000,-259.307089,-0.0,...,1.094023e-01,1.0,-0.0,-0.0,7.156638e-01,-0.0,-377.225875,-62.728343,61.061953,39.207947
13,NaN,Zj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,-0.000055,0.0,...,-5.500000e-07,0.0,0.0,0.0,5.800000e-07,0.0,-0.000076,-1.000013,-0.999988,NaN
14,NaN,Cj - Zj,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.000055,0.0,...,5.500000e-07,0.0,0.0,0.0,-5.800000e-07,0.0,0.000076,1.000013,0.999988,NaN

Any of [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.503e-05, 0.0, 0.0, 5.5e-07, 0.0, 0.0, 0.0, -5.8e-07, 0.0, 7.556e-05, 1.00001316, 0.99998765] is not >= 0, optimal solution is not found yet.
Proceed to next step.

Iteration 10:
a) Key column is S8 because -5.8e-07 is the smallest value of Cj - Zj.
b)

,CBi,Basic Variable,X1,X2,X3,X4,X5,X7,S1,S2,...,S5,S6,S7,S8,S9,S10,S11,S12,Solution,Ratio
0,NaN,Cj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,0.000000,0.0,...,0.0,0.0,0.0,0.000000e+00,0.0,0.000000,0.000000,0.000000,NaN,NaN
1,-135.5611,X1,1.0000,0.0000,0.0000,0.0000,0.0000,0.000,1.000000,0.0,...,0.0,0.0,0.0,0.000000e+00,0.0,0.000000,0.000000,0.000000,0.980000,NaN
2,0.0000,S2,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,259.307089,1.0,...,0.0,0.0,0.0,1.284336e+00,0.0,377.225875,62.728343,-61.061953,218.042053,169.770231
3,0.0000,S3,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,-13.885308,0.0,...,0.0,0.0,0.0,2.866538e-02,0.0,7.298447,0.638443,-0.388045,0.838580,29.254105
4,-0.1287,X2,0.0000,1.0000,0.0000,0.0000,0.0000,0.000,-259.307089,0.0,...,0.0,0.0,0.0,-1.284336e+00,0.0,-377.225875,-62.728343,61.061953,590.457947,-459.737837
5,0.0000,S7,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.000000,0.0,...,0.0,0.0,1.0,0.000000e+00,0.0,0.000000,-1.000000,1.000000,2.660000,NaN
6,0.0000,S6,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.000000,0.0,...,0.0,1.0,0.0,0.000000e+00,0.0,0.000000,1.000000,-1.000000,2.660000,NaN
7,0.0586,X3,0.0000,0.0000,1.0000,0.0000,0.0000,0.000,-259.307089,0.0,...,0.0,0.0,0.0,-2.843362e-01,0.0,-377.225875,-62.728343,61.061953,296.457947,-1042.631741
8,8.4538,X5,0.0000,0.0000,0.0000,0.0000,1.0000,0.000,13.885308,0.0,...,0.0,0.0,0.0,-2.866538e-02,0.0,-7.298447,-0.638443,0.388045,2.661420,-92.844398
9,0.0000,S9,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,-13.885308,0.0,...,0.0,0.0,0.0,2.866538e-02,1.0,7.298447,0.638443,-0.388045,4.338580,151.352609
10,35.2560,X7,0.0000,0.0000,0.0000,0.0000,0.0000,1.000,0.000000,0.0,...,0.0,0.0,0.0,0.000000e+00,0.0,1.000000,0.000000,0.000000,0.400000,NaN
11,-0.0937,X4,0.0000,0.0000,0.0000,1.0000,0.0000,0.000,0.000000,0.0,...,0.0,0.0,0.0,-1.000000e+00,0.0,0.000000,0.000000,0.000000,110.250000,-110.250000
12,0.0000,S5,-0.0000,-0.0000,-0.0000,-0.0000,-0.0000,-0.000,-259.307089,-0.0,...,1.0,-0.0,-0.0,7.156638e-01,-0.0,-377.225875,-62.728343,61.061953,39.207947,54.785427
13,NaN,Zj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,-0.000055,0.0,...,0.0,0.0,0.0,5.800000e-07,0.0,-0.000076,-1.000013,-0.999988,NaN,NaN
14,NaN,Cj - Zj,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.000055,0.0,...,0.0,0.0,0.0,-5.800000e-07,0.0,0.000076,1.000013,0.999988,NaN,NaN

Key row is S3 because 29.25410513 is the smallest non-negative value of Ratio.
c) Key element is 0.02866538 located at (S3, S8).
d) S8 is entering variable while S3 is departing variable.
e) Filling in the elements:

,CBi,Basic Variable,X1,X2,X3,X4,X5,X7,S1,S2,...,S4,S5,S6,S7,S8,S9,S10,S11,S12,Solution
0,NaN,Cj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,0.000000,0.0,...,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,NaN
1,-135.5611,X1,1.0000,0.0000,0.0000,0.0000,0.0000,0.000,1.000000,0.0,...,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.980000
2,0.0000,S2,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,881.430497,1.0,...,2.491411e-01,0.0,0.0,0.0,0.0,0.0,50.223079,34.123261,-43.675813,180.469947
3,0.0000,S8,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,-484.392956,0.0,...,4.994460e-01,0.0,0.0,0.0,1.0,0.0,254.608408,22.272270,-13.537063,29.254105
4,-0.1287,X2,0.0000,1.0000,0.0000,0.0000,0.0000,0.000,-881.430497,0.0,...,-2.491411e-01,0.0,0.0,0.0,0.0,0.0,-50.223079,-34.123261,43.675813,628.030053
5,0.0000,S7,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.000000,0.0,...,0.000000e+00,0.0,0.0,1.0,0.0,0.0,0.000000,-1.000000,1.000000,2.660000
6,0.0000,S6,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.000000,0.0,...,0.000000e+00,0.0,1.0,0.0,0.0,0.0,0.000000,1.000000,-1.000000,2.660000
7,0.0586,X3,0.0000,0.0000,1.0000,0.0000,0.0000,0.000,-397.037541,0.0,...,2.514129e-01,0.0,0.0,0.0,0.0,0.0,-304.831488,-56.395531,57.212876,304.775948
8,8.4538,X5,0.0000,0.0000,0.0000,0.0000,1.0000,0.000,0.000000,0.0,...,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,3.500000
9,0.0000,S9,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.000000,0.0,...,0.000000e+00,0.0,0.0,0.0,0.0,1.0,0.000000,0.000000,0.000000,3.500000
10,35.2560,X7,0.0000,0.0000,0.0000,0.0000,0.0000,1.000,0.000000,0.0,...,0.000000e+00,0.0,0.0,0.0,0.0,0.0,1.000000,0.000000,0.000000,0.400000
11,-0.0937,X4,0.0000,0.0000,0.0000,1.0000,0.0000,0.000,-484.392956,0.0,...,4.994460e-01,0.0,0.0,0.0,0.0,0.0,254.608408,22.272270,-13.537063,139.504105
12,0.0000,S5,-0.0000,-0.0000,-0.0000,-0.0000,-0.0000,-0.000,87.355414,-0.0,...,-2.480332e-01,1.0,-0.0,-0.0,0.0,-0.0,-559.439896,-78.667800,70.749939,18.271843
13,NaN,Zj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,0.000225,0.0,...,-8.400000e-07,0.0,0.0,0.0,0.0,0.0,-0.000223,-1.000026,-0.999980,NaN
14,NaN,Cj - Zj,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,-0.000225,0.0,...,8.400000e-07,0.0,0.0,0.0,0.0,0.0,0.000223,1.000026,0.999980,NaN

Any of [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.00022504, 0.0, -2.017e-05, 8.4e-07, 0.0, 0.0, 0.0, 0.0, 0.0, 0.00022277, 1.00002603, 0.99997982] is not >= 0, optimal solution is not found yet.
Proceed to next step.

Iteration 11:
a) Key column is S1 because -0.00022504 is the smallest value of Cj - Zj.
b)

,CBi,Basic Variable,X1,X2,X3,X4,X5,X7,S1,S2,...,S5,S6,S7,S8,S9,S10,S11,S12,Solution,Ratio
0,NaN,Cj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,NaN,NaN
1,-135.5611,X1,1.0000,0.0000,0.0000,0.0000,0.0000,0.000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.980000,0.980000
2,0.0000,S2,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,881.430497,1.0,...,0.0,0.0,0.0,0.0,0.0,50.223079,34.123261,-43.675813,180.469947,0.204747
3,0.0000,S8,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,-484.392956,0.0,...,0.0,0.0,0.0,1.0,0.0,254.608408,22.272270,-13.537063,29.254105,-0.060393
4,-0.1287,X2,0.0000,1.0000,0.0000,0.0000,0.0000,0.000,-881.430497,0.0,...,0.0,0.0,0.0,0.0,0.0,-50.223079,-34.123261,43.675813,628.030053,-0.712512
5,0.0000,S7,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.000000,0.0,...,0.0,0.0,1.0,0.0,0.0,0.000000,-1.000000,1.000000,2.660000,NaN
6,0.0000,S6,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.000000,0.0,...,0.0,1.0,0.0,0.0,0.0,0.000000,1.000000,-1.000000,2.660000,NaN
7,0.0586,X3,0.0000,0.0000,1.0000,0.0000,0.0000,0.000,-397.037541,0.0,...,0.0,0.0,0.0,0.0,0.0,-304.831488,-56.395531,57.212876,304.775948,-0.767625
8,8.4538,X5,0.0000,0.0000,0.0000,0.0000,1.0000,0.000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,3.500000,NaN
9,0.0000,S9,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.000000,0.0,...,0.0,0.0,0.0,0.0,1.0,0.000000,0.000000,0.000000,3.500000,NaN
10,35.2560,X7,0.0000,0.0000,0.0000,0.0000,0.0000,1.000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,1.000000,0.000000,0.000000,0.400000,NaN
11,-0.0937,X4,0.0000,0.0000,0.0000,1.0000,0.0000,0.000,-484.392956,0.0,...,0.0,0.0,0.0,0.0,0.0,254.608408,22.272270,-13.537063,139.504105,-0.287998
12,0.0000,S5,-0.0000,-0.0000,-0.0000,-0.0000,-0.0000,-0.000,87.355414,-0.0,...,1.0,-0.0,-0.0,0.0,-0.0,-559.439896,-78.667800,70.749939,18.271843,0.209167
13,NaN,Zj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,0.000225,0.0,...,0.0,0.0,0.0,0.0,0.0,-0.000223,-1.000026,-0.999980,NaN,NaN
14,NaN,Cj - Zj,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,-0.000225,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000223,1.000026,0.999980,NaN,NaN

Key row is S2 because 0.20474666 is the smallest non-negative value of Ratio.
c) Key element is 881.43049723 located at (S2, S1).
d) S1 is entering variable while S2 is departing variable.
e) Filling in the elements:

,CBi,Basic Variable,X1,X2,X3,X4,X5,X7,S1,S2,...,S4,S5,S6,S7,S8,S9,S10,S11,S12,Solution
0,NaN,Cj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,0.0,0.000000e+00,...,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,NaN
1,-135.5611,X1,1.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.0,-1.134520e-03,...,-2.826600e-04,0.0,0.0,0.0,0.0,0.0,-0.056979,-0.038713,0.049551,0.775253
2,0.0000,S1,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,1.0,1.134520e-03,...,2.826600e-04,0.0,0.0,0.0,0.0,0.0,0.056979,0.038713,-0.049551,0.204747
3,0.0000,S8,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.0,5.495532e-01,...,6.363623e-01,0.0,0.0,0.0,1.0,0.0,282.208663,41.024817,-37.539246,128.431943
4,-0.1287,X2,0.0000,1.0000,0.0000,0.0000,0.0000,0.000,0.0,1.000000e+00,...,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,808.500000
5,0.0000,S7,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.0,0.000000e+00,...,0.000000e+00,0.0,0.0,1.0,0.0,0.0,0.000000,-1.000000,1.000000,2.660000
6,0.0000,S6,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.0,0.000000e+00,...,0.000000e+00,0.0,1.0,0.0,0.0,0.0,0.000000,1.000000,-1.000000,2.660000
7,0.0586,X3,0.0000,0.0000,1.0000,0.0000,0.0000,0.000,0.0,4.504468e-01,...,3.636377e-01,0.0,0.0,0.0,0.0,0.0,-282.208663,-41.024817,37.539246,386.068057
8,8.4538,X5,0.0000,0.0000,0.0000,0.0000,1.0000,0.000,0.0,0.000000e+00,...,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,3.500000
9,0.0000,S9,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.0,0.000000e+00,...,0.000000e+00,0.0,0.0,0.0,0.0,1.0,0.000000,0.000000,0.000000,3.500000
10,35.2560,X7,0.0000,0.0000,0.0000,0.0000,0.0000,1.000,0.0,0.000000e+00,...,0.000000e+00,0.0,0.0,0.0,0.0,0.0,1.000000,0.000000,0.000000,0.400000
11,-0.0937,X4,0.0000,0.0000,0.0000,1.0000,0.0000,0.000,0.0,5.495532e-01,...,6.363623e-01,0.0,0.0,0.0,0.0,0.0,282.208663,41.024817,-37.539246,238.681943
12,0.0000,S5,-0.0000,-0.0000,-0.0000,-0.0000,-0.0000,-0.000,0.0,-9.910641e-02,...,-2.727247e-01,1.0,-0.0,-0.0,0.0,-0.0,-564.417325,-82.049634,75.078492,0.386114
13,NaN,Zj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,0.0,-1.700000e-07,...,-2.800000e-07,0.0,0.0,0.0,0.0,0.0,-0.000235,-1.000035,-0.999969,NaN
14,NaN,Cj - Zj,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.0,1.700000e-07,...,2.800000e-07,0.0,0.0,0.0,0.0,0.0,0.000235,1.000035,0.999969,NaN

Any of [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.7e-07, -8.39e-06, 2.8e-07, 0.0, 0.0, 0.0, 0.0, 0.0, 0.00023526, 1.00003501, 0.99996905] is not >= 0, optimal solution is not found yet.
Proceed to next step.

Iteration 12:
a) Key column is S3 because -8.39e-06 is the smallest value of Cj - Zj.
b)

,CBi,Basic Variable,X1,X2,X3,X4,X5,X7,S1,S2,...,S5,S6,S7,S8,S9,S10,S11,S12,Solution,Ratio
0,NaN,Cj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,0.0,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,NaN,NaN
1,-135.5611,X1,1.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.0,-1.134520e-03,...,0.0,0.0,0.0,0.0,0.0,-0.056979,-0.038713,0.049551,0.775253,-15.251435
2,0.0000,S1,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,1.0,1.134520e-03,...,0.0,0.0,0.0,0.0,0.0,0.056979,0.038713,-0.049551,0.204747,4.027948
3,0.0000,S8,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.0,5.495532e-01,...,0.0,0.0,0.0,1.0,0.0,282.208663,41.024817,-37.539246,128.431943,-12.514239
4,-0.1287,X2,0.0000,1.0000,0.0000,0.0000,0.0000,0.000,0.0,1.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,808.500000,NaN
5,0.0000,S7,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.0,0.000000e+00,...,0.0,0.0,1.0,0.0,0.0,0.000000,-1.000000,1.000000,2.660000,NaN
6,0.0000,S6,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.0,0.000000e+00,...,0.0,1.0,0.0,0.0,0.0,0.000000,1.000000,-1.000000,2.660000,NaN
7,0.0586,X3,0.0000,0.0000,1.0000,0.0000,0.0000,0.000,0.0,4.504468e-01,...,0.0,0.0,0.0,0.0,0.0,-282.208663,-41.024817,37.539246,386.068057,37.617961
8,8.4538,X5,0.0000,0.0000,0.0000,0.0000,1.0000,0.000,0.0,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,3.500000,-3.500000
9,0.0000,S9,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.0,0.000000e+00,...,0.0,0.0,0.0,0.0,1.0,0.000000,0.000000,0.000000,3.500000,3.500000
10,35.2560,X7,0.0000,0.0000,0.0000,0.0000,0.0000,1.000,0.0,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,1.000000,0.000000,0.000000,0.400000,NaN
11,-0.0937,X4,0.0000,0.0000,0.0000,1.0000,0.0000,0.000,0.0,5.495532e-01,...,0.0,0.0,0.0,0.0,0.0,282.208663,41.024817,-37.539246,238.681943,-23.256853
12,0.0000,S5,-0.0000,-0.0000,-0.0000,-0.0000,-0.0000,-0.000,0.0,-9.910641e-02,...,1.0,-0.0,-0.0,0.0,-0.0,-564.417325,-82.049634,75.078492,0.386114,0.018811
13,NaN,Zj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,0.0,-1.700000e-07,...,0.0,0.0,0.0,0.0,0.0,-0.000235,-1.000035,-0.999969,NaN,NaN
14,NaN,Cj - Zj,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.0,1.700000e-07,...,0.0,0.0,0.0,0.0,0.0,0.000235,1.000035,0.999969,NaN,NaN

Key row is S5 because 0.01881122 is the smallest non-negative value of Ratio.
c) Key element is 20.52572988 located at (S5, S3).
d) S3 is entering variable while S5 is departing variable.
e) Filling in the elements:

,CBi,Basic Variable,X1,X2,X3,X4,X5,X7,S1,S2,...,S4,S5,S6,S7,S8,S9,S10,S11,S12,Solution
0,NaN,Cj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,0.0,0.000000e+00,...,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,NaN
1,-135.5611,X1,1.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.0,-1.379950e-03,...,-9.580600e-04,2.476480e-03,0.0,0.0,0.0,0.0,-1.454746e+00,-2.419075e-01,0.235481,0.776210
2,0.0000,S1,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,1.0,1.379950e-03,...,9.580600e-04,-2.476480e-03,0.0,0.0,0.0,0.0,1.454746e+00,2.419075e-01,-0.235481,0.203790
3,0.0000,S8,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.0,5.000000e-01,...,5.000000e-01,5.000000e-01,0.0,0.0,1.0,0.0,-1.000000e-08,1.000000e-08,-0.000000,128.625000
4,-0.1287,X2,0.0000,1.0000,0.0000,0.0000,0.0000,0.000,0.0,1.000000e+00,...,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,808.500000
5,0.0000,S7,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.0,0.000000e+00,...,0.000000e+00,0.000000e+00,0.0,1.0,0.0,0.0,0.000000e+00,-1.000000e+00,1.000000,2.660000
6,0.0000,S6,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.0,0.000000e+00,...,0.000000e+00,0.000000e+00,1.0,0.0,0.0,0.0,0.000000e+00,1.000000e+00,-1.000000,2.660000
7,0.0586,X3,0.0000,0.0000,1.0000,0.0000,0.0000,0.000,0.0,5.000000e-01,...,5.000000e-01,-5.000000e-01,0.0,0.0,0.0,0.0,2.000000e-08,1.000000e-08,0.000000,385.875000
8,8.4538,X5,0.0000,0.0000,0.0000,0.0000,1.0000,0.000,0.0,-4.828400e-03,...,-1.328697e-02,4.871934e-02,0.0,0.0,0.0,0.0,-2.749804e+01,-3.997404e+00,3.657775,3.518811
9,0.0000,S9,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.0,4.828400e-03,...,1.328697e-02,-4.871934e-02,0.0,0.0,0.0,1.0,2.749804e+01,3.997404e+00,-3.657775,3.481189
10,35.2560,X7,0.0000,0.0000,0.0000,0.0000,0.0000,1.000,0.0,0.000000e+00,...,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,1.000000e+00,0.000000e+00,0.000000,0.400000
11,-0.0937,X4,0.0000,0.0000,0.0000,1.0000,0.0000,0.000,0.0,5.000000e-01,...,5.000000e-01,5.000000e-01,0.0,0.0,0.0,0.0,-1.000000e-08,1.000000e-08,-0.000000,238.875000
12,0.0000,S3,-0.0000,-0.0000,-0.0000,-0.0000,-0.0000,-0.000,0.0,-4.828400e-03,...,-1.328697e-02,4.871934e-02,-0.0,-0.0,0.0,-0.0,-2.749804e+01,-3.997404e+00,3.657775,0.018811
13,NaN,Zj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,0.0,-7.900000e-07,...,2.800000e-07,-8.000000e-07,0.0,0.0,0.0,0.0,-4.780000e-06,-1.000002e+00,-1.000000,NaN
14,NaN,Cj - Zj,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.0,7.900000e-07,...,-2.800000e-07,8.000000e-07,0.0,0.0,0.0,0.0,4.780000e-06,1.000002e+00,1.000000,NaN

Any of [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 7.9e-07, 0.0, -2.8e-07, 8e-07, 0.0, 0.0, 0.0, 0.0, 4.78e-06, 1.00000155, 1.00000033] is not >= 0, optimal solution is not found yet.
Proceed to next step.

Iteration 13:
a) Key column is S4 because -2.8e-07 is the smallest value of Cj - Zj.
b)

,CBi,Basic Variable,X1,X2,X3,X4,X5,X7,S1,S2,...,S5,S6,S7,S8,S9,S10,S11,S12,Solution,Ratio
0,NaN,Cj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,0.0,0.000000e+00,...,0.000000e+00,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,NaN,NaN
1,-135.5611,X1,1.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.0,-1.379950e-03,...,2.476480e-03,0.0,0.0,0.0,0.0,-1.454746e+00,-2.419075e-01,0.235481,0.776210,-810.188861
2,0.0000,S1,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,1.0,1.379950e-03,...,-2.476480e-03,0.0,0.0,0.0,0.0,1.454746e+00,2.419075e-01,-0.235481,0.203790,212.711584
3,0.0000,S8,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.0,5.000000e-01,...,5.000000e-01,0.0,0.0,1.0,0.0,-1.000000e-08,1.000000e-08,-0.000000,128.625000,257.250000
4,-0.1287,X2,0.0000,1.0000,0.0000,0.0000,0.0000,0.000,0.0,1.000000e+00,...,0.000000e+00,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,808.500000,NaN
5,0.0000,S7,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.0,0.000000e+00,...,0.000000e+00,0.0,1.0,0.0,0.0,0.000000e+00,-1.000000e+00,1.000000,2.660000,NaN
6,0.0000,S6,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.0,0.000000e+00,...,0.000000e+00,1.0,0.0,0.0,0.0,0.000000e+00,1.000000e+00,-1.000000,2.660000,NaN
7,0.0586,X3,0.0000,0.0000,1.0000,0.0000,0.0000,0.000,0.0,5.000000e-01,...,-5.000000e-01,0.0,0.0,0.0,0.0,2.000000e-08,1.000000e-08,0.000000,385.875000,771.750000
8,8.4538,X5,0.0000,0.0000,0.0000,0.0000,1.0000,0.000,0.0,-4.828400e-03,...,4.871934e-02,0.0,0.0,0.0,0.0,-2.749804e+01,-3.997404e+00,3.657775,3.518811,-264.831728
9,0.0000,S9,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.0,4.828400e-03,...,-4.871934e-02,0.0,0.0,0.0,1.0,2.749804e+01,3.997404e+00,-3.657775,3.481189,262.000199
10,35.2560,X7,0.0000,0.0000,0.0000,0.0000,0.0000,1.000,0.0,0.000000e+00,...,0.000000e+00,0.0,0.0,0.0,0.0,1.000000e+00,0.000000e+00,0.000000,0.400000,NaN
11,-0.0937,X4,0.0000,0.0000,0.0000,1.0000,0.0000,0.000,0.0,5.000000e-01,...,5.000000e-01,0.0,0.0,0.0,0.0,-1.000000e-08,1.000000e-08,-0.000000,238.875000,477.750000
12,0.0000,S3,-0.0000,-0.0000,-0.0000,-0.0000,-0.0000,-0.000,0.0,-4.828400e-03,...,4.871934e-02,-0.0,-0.0,0.0,-0.0,-2.749804e+01,-3.997404e+00,3.657775,0.018811,-1.415764
13,NaN,Zj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,0.0,-7.900000e-07,...,-8.000000e-07,0.0,0.0,0.0,0.0,-4.780000e-06,-1.000002e+00,-1.000000,NaN,NaN
14,NaN,Cj - Zj,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.0,7.900000e-07,...,8.000000e-07,0.0,0.0,0.0,0.0,4.780000e-06,1.000002e+00,1.000000,NaN,NaN

Key row is S1 because 212.71158383 is the smallest non-negative value of Ratio.
c) Key element is 0.00095806 located at (S1, S4).
d) S4 is entering variable while S1 is departing variable.
e) Filling in the elements:

,CBi,Basic Variable,X1,X2,X3,X4,X5,X7,S1,S2,...,S4,S5,S6,S7,S8,S9,S10,S11,S12,Solution
0,NaN,Cj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,0.000000,0.000000,...,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,NaN
1,-135.5611,X1,1.0000,0.0000,0.0000,0.0000,0.0000,0.000,1.000000,0.000000,...,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.980000
2,0.0000,S4,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,1043.775964,1.440359,...,1.0,-2.584890e+00,0.0,0.0,0.0,0.0,1518.428533,252.497276,-245.789648,212.711584
3,0.0000,S8,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,-521.887982,-0.220179,...,0.0,1.792445e+00,0.0,0.0,1.0,0.0,-759.214266,-126.248638,122.894824,22.269208
4,-0.1287,X2,0.0000,1.0000,0.0000,0.0000,0.0000,0.000,0.000000,1.000000,...,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,808.500000
5,0.0000,S7,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.000000,0.000000,...,0.0,0.000000e+00,0.0,1.0,0.0,0.0,0.000000,-1.000000,1.000000,2.660000
6,0.0000,S6,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.000000,0.000000,...,0.0,0.000000e+00,1.0,0.0,0.0,0.0,0.000000,1.000000,-1.000000,2.660000
7,0.0586,X3,0.0000,0.0000,1.0000,0.0000,0.0000,0.000,-521.887982,-0.220179,...,0.0,7.924452e-01,0.0,0.0,0.0,0.0,-759.214266,-126.248638,122.894824,279.519208
8,8.4538,X5,0.0000,0.0000,0.0000,0.0000,1.0000,0.000,13.868620,0.014310,...,-0.0,1.437398e-02,0.0,0.0,0.0,0.0,-7.322725,-0.642480,0.391975,6.345104
9,0.0000,S9,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,-13.868620,-0.014310,...,0.0,-1.437398e-02,0.0,0.0,0.0,1.0,7.322725,0.642480,-0.391975,0.654896
10,35.2560,X7,0.0000,0.0000,0.0000,0.0000,0.0000,1.000,0.000000,0.000000,...,0.0,0.000000e+00,0.0,0.0,0.0,0.0,1.000000,0.000000,0.000000,0.400000
11,-0.0937,X4,0.0000,0.0000,0.0000,1.0000,0.0000,0.000,-521.887982,-0.220179,...,0.0,1.792445e+00,0.0,0.0,0.0,0.0,-759.214266,-126.248638,122.894824,132.519208
12,0.0000,S3,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,13.868620,0.014310,...,-0.0,1.437398e-02,0.0,0.0,0.0,0.0,-7.322725,-0.642480,0.391975,2.845104
13,NaN,Zj,-135.5611,-0.1287,0.0586,-0.0937,8.4538,35.256,-0.000293,-0.000001,...,0.0,-7.000000e-08,0.0,0.0,0.0,0.0,-0.000431,-1.000072,-0.999931,NaN
14,NaN,Cj - Zj,0.0000,0.0000,0.0000,0.0000,0.0000,0.000,0.000293,0.000001,...,0.0,7.000000e-08,0.0,0.0,0.0,0.0,0.000431,1.000072,0.999931,NaN

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.00029275, 1.21e-06, 0.0, 0.0, 7e-08, 0.0, 0.0, 0.0, 0.0, 0.00043067, 1.00007235, 0.99993142] are >= 0, optimal solution is found successfully!
13 iterations taken.
Final solution:

                  Solution
Basic Variable
X1                0.980000
S4              212.711584
S8               22.269208
X2              808.500000
S7                2.660000
S6                2.660000
X3              279.519208
X5                6.345104
S9                0.654896
X7                0.400000
X4              132.519208
S3                2.845104

In [17]:
# Solution
X1 = round(df_simpx_final.loc['X1', 'Solution'], 2)
X2 = round(df_simpx_final.loc['X2', 'Solution'], 2)
X3 = round(df_simpx_final.loc['X3', 'Solution'], 2)
X4 = round(df_simpx_final.loc['X4', 'Solution'], 2)
X5 = round(df_simpx_final.loc['X5', 'Solution'], 2)
X7 = round(df_simpx_final.loc['X7', 'Solution'], 2)

print('Variables:')
print(f'X1 = {X1}')
print(f'X2 = {X2}')
print(f'X3 = {X3}')
print(f'X4 = {X4}')
print(f'X5 = {X5}')
print(f'X7 = {X7}')


Y1 = round(round(lm1.params[0], decimal) + round(lm1.params['X1'], decimal) * X1 + round(lm1.params['X2'], decimal) * X2 + \
     round(lm1.params['X3'], decimal) * X3 + round(lm1.params['X4'], decimal) * X4 + round(lm1.params['X5'], decimal) * X5 + \
     round(lm1.params['X7'], decimal) * X7, decimal)
Y2 = round(round(lm2.params[0], decimal) + round(lm2.params['X1'], decimal) * X1 + round(lm2.params['X2'], decimal) * X2 + \
     round(lm2.params['X3'], decimal) * X3 + round(lm2.params['X4'], decimal) * X4 + round(lm2.params['X5'], decimal) * X5 + \
     round(lm2.params['X7'], decimal) * X7, decimal)
Z = round(Z_intercept + X1_coef * X1 + X2_coef * X2 + X3_coef * X3 + X4_coef * X4 + X5_coef * X5 + X7_coef * X7, 2)

print('\nSolution:')
print(f'Y1 = {Y1}')
print(f'Y2 = {Y2}')
print(f'Z = {Z}')

Variables:
X1 = 0.98
X2 = 808.5
X3 = 279.52
X4 = 132.52
X5 = 6.35
X7 = 0.4

Solution:
Y1 = 8.4954
Y2 = 8.4959
Z = 16.99